### ISSUE TITLE
TimerInfo.ScheduleStatus.Next does not indicate the next occurence

### ISSUE THREAD

**Issue by Archomeda** [Azure/azure-functions-dotnet-worker#954] opened 2022-07-01 10:03 UTC
I've noticed with our timer triggered function, that the TimerInfo.ScheduleStatus.Next value always seems to be the **current** trigger time, and **not** the next. The documentation also says "Gets or sets the expected next schedule occurrence".

So I'm expecting the following when the cron is set to `0 */10 * * * *`, and the function is triggered at `2022-07-01T09:30:00.0024370+00:00`:
- Last: `7/1/2022 9:20:00 AM`
- Next: `7/1/2022 9:40:00 AM`

But instead I'm seeing the following:
- Last: `7/1/2022 9:20:00 AM`
- Next: `7/1/2022 9:30:00 AM`

Looking at this, for me *last* means the previous run, and *next* means the next run. In this case, I'm actually missing a *current* property.

The documentation seems to be very ambiguous in this regard. Can someone clarify what is intended here, and possibly update the documentation? Or, even better, consider adding `Current` and change `Last` to `Previous`.

**Comment by fabiocav** [comment] 2022-08-03 20:09
Investigation on this is in progress. Moving to sprint 128 so we can continue to track.

**Comment by mathewc** [comment] 2022-09-06 17:06
ScheduleStatus is a structure persisted to storage to aid in detection of past due schedule invocations. As the class xml doc says, Next is “the next schedule occurrence”.  So on startup, if schedule monitoring is active, we’ll load the ScheduleStatus (code [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/b493a05b47c15c053a8df54f13954525e9d462e8/src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs#L104)) and use Next to determine how long to wait before the next invocation (Next - Now). Thus, when this duration expires, we’ll invoke the function and Next will equal Now.

So Next isn’t the next schedule time from the current invocation – it’s the value that was used to determine when to invoke the current invocation. The naming of the properties of ScheduleStatus are from the perspective of the scheduler, not from the perspective of the current invocation.

If the goal is to determine the next expected invocation from the time of the current invocation, the schedule can be used as follows to determine that:

```csharp
public static void CronJob([TimerTrigger("*/15 * * * * *")] TimerInfo timerInfo)
{
    var schedule = timerInfo.Schedule as CronSchedule;
    var next = schedule.GetNextOccurrence(DateTime.UtcNow);

    . . .
}
```

If this explanation isn't clear or if we keep getting customer confusion on this, we can consider updating the xml doc for these properties to clarify this.

**Comment by mathewc** [comment] 2022-09-06 17:18
I have a PR https://github.com/Azure/azure-webjobs-sdk-extensions/pull/797 with a proposed update - if this helps we can make it.

**Comment by mathewc** [comment] 2022-09-06 19:53
Closing as by design, as per the above explanations. We've also made an update to the xml doc.

**Closed by mathewc** 2022-09-06 19:53 UTC
Labels: needs-investigation, Needs: Attention :wave:

**Comment by nickjmcclure** [comment] 2022-10-05 04:55
@mathewc I understand the explanation, but I think there should probably be an update to Timer Trigger template that is used in visual studio as well. when creating a new trigger, the template includes the following code:
```csharp
  [Function("FunctionTest")]
  public void Run([TimerTrigger("0 */5 * * * *")] MyInfo myTimer)
  {
      _logger.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
      _logger.LogInformation($"Next timer schedule at: {myTimer.ScheduleStatus.Next}");
  }
```

I think this also implies the ```ScheduleStatus.Next``` property will hold the date/time of the next invocation, not the current.

**Comment by mathewc** [comment] 2022-10-05 18:47
@nickjmcclure Yes, please log your issue in the templates repo here https://github.com/Azure/azure-functions-templates/issues
