### ISSUE TITLE
Failed to start a new language worker for runtime: dotnet-isolated

### ISSUE THREAD

**Issue by johan-lindqvist** [Azure/azure-functions-dotnet-worker#1458] opened 2023-04-11 07:39 UTC
We keep getting errors saying `Failed to start a new language worker for runtime: dotnet-isolated`, it happens about 1-3 times a day (I assume it has to do with scaling and starting up a new worker). I can see in the application insight logs that sometimes it does start accepting requests after it has failed to launch it if I search for the host instance id, but sometimes the host instance id has no more logs after it fails to start the worker.

```
System.TimeoutException:
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel+PendingItem.OnTimeout (Microsoft.Azure.WebJobs.Script.Grpc, Version=4.17.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:1452)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel+<StartWorkerProcessAsync>d__55.MoveNext (Microsoft.Azure.WebJobs.Script.Grpc, Version=4.17.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:275)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher+<InitializeJobhostLanguageWorkerChannelAsync>d__50.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.17.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:152)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher+<InitializeJobhostLanguageWorkerChannelAsync>d__49.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.17.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:144)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher+<InitializeJobhostLanguageWorkerChannelAsync>d__48.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.17.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:135)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher+<>c__DisplayClass55_0+<<StartWorkerProcesses>b__0>d.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.17.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:215)
```

Requests still get through since it will start another worker eventually, but it is very annoying to see these logs since we have alarms when we get logs with the ERROR log level. Also I assume this will result in a performance degradation. The response to the caller will be `502 Bad Gateway`, which causes issues in integration tests and such.

Checking the logs for the host instance id it seems like the function version is 4.17.3.

I also get this log before the error so it seems like it's starting something but then times out for some reason:
```
Host started (3307ms)
```

**Comment by ErikRosengren-work** [comment] 2023-04-25 13:13
We are also having this issue... Is there an update @satvu?

**Comment by johan-lindqvist** [comment] 2023-04-27 07:48
Still getting this multiple times per day. The host is using function version 4.19.0 now and the issue remains.

**Comment by satvu** [comment] 2023-04-27 17:03
@ErikRosengren-work @johan-lindqvist We are actively investigating similar reports, and two different suggestions for mitigation/resolution are:

1. Pin 4.16 to see if the issue is mitigated.
2. Add more logging around DI Startup code to see if DI code works as expected (an exception might cause a Timeout error in 4.17 runtime). You can reference [this comment](https://github.com/Azure/azure-functions-host/issues/5206#issuecomment-553608849) to set this up.

Additionally, could you both share which worker version and dotnet version you are using?

**Comment by johan-lindqvist** [comment] 2023-04-28 06:36
We've tried multiple versions. 
Currently we're using ~4 in our bicep files, checking the logs it says the following:
```
Starting Host (HostId=<function-app-name>, InstanceId=<instance-id>, Version=4.19.0.20414, ProcessId=3756, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=~4)
```

We've also seen the issue with `4.17.3`.

We previously tried pinning 4.14, which did not help.

I'll try pinning 4.16 and see if that helps.

About the comment regarding DI code, we've tried adding logging at the first line in our function entry method and in our constructor and we never reach our code at all, so I doubt that it is due to DI, it has to happen when the host is trying to start our isolated process and for some reason it never even starts our process at all.

**Comment by johan-lindqvist** [comment] 2023-05-04 06:05
Pinning to `4.16` fixed the issue, or at least it stopped us from getting the error logs.

**Comment by satvu** [comment] 2023-05-08 16:34
We believe this is related to a race condition in worker version 1.13 - this was fixed in https://github.com/Azure/azure-functions-dotnet-worker/pull/1508. Please unpin the host version and upgrade to the latest worker package [1.14.1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.14.1).

Related issue https://github.com/Azure/azure-functions-dotnet-worker/issues/1514.

**Closed by satvu** 2023-05-08 16:34 UTC
Labels: Needs: Attention :wave:

**Comment by hbrotan** [comment] 2023-05-08 16:51
I can confirm that our errors disappeared after upgrading to 1.14.1.

**Comment by gmantri** [comment] 2023-05-19 06:44
I am facing same problems though I am on worker package 1.14.1. I have a .Net 7 isolated function with Service Bus Topic input binding.

```
        <PackageReference Include="Azure.Identity" Version="1.9.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.14.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview4" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.7.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.10.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="6.0.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="7.0.5" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
```

One of the errors that is getting logged in App Insights is `Unhandled exception. System.InvalidOperationException: The gRPC channel URI 'http://:0' could not be parsed.`. 

I even tried pinning the version to 4.16 by going to Function App Configuration > App Configuration and changing the value of `FUNCTIONS_EXTENSION_VERSION` settings from `~4` to `4.16` but that did not make any difference. On the overview page, I still see the version as `4.21.1.20667`.

Can someone tell me what I am doing wrong or how to fix this issue? The code works perfectly fine on my local machine.
