### ISSUE TITLE
Function with Service Bus dependency hangs

### ISSUE THREAD

**Issue by fabio-marini** [Azure/azure-functions-dotnet-worker#913] opened 2022-05-27 07:19 UTC
- Visual Studio Professional 2022 (Version 17.2.2)
- .NET 6 Isolated Function App project (C#)

![image](https://user-images.githubusercontent.com/10209472/170648456-adfb1747-0696-4038-b1e5-29a1dcdd62c8.png)

You can see in the screenshot above that the vanilla `Function1` completes as expected.

However, `Function2`, which has a dependency on the `Azure.Messaging.ServiceBus` package, hangs, i.e.:
- the expected `Executed 'Functions.Function2'...` log line is never printed
- Postman (running in the background) is stuck on sending the request.

Have tried both Azurite and the legacy Storage Emulator, just in case, but it made no difference.

[This](https://github.com/fabio-marini/functions-worker-issue-913) should allow you to reproduce the issue, just add a `local.settings.json`...

**Comment by kshyju** [comment] 2022-05-27 17:10
@fabio-marini Thanks for reporting. This issue is same as #833 

The `ServiceBusClient` class (_in [version 7.8.1](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.8.1)_) does not implement `IDisposable`, [but IAsyncDisposable](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Client/ServiceBusClient.cs#L20).  So [this line](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Context/DefaultFunctionContext.cs#L65) throws with below exception.

> 'Azure.Messaging.ServiceBus.ServiceBusClient' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.

We will release a fix for this and will share an update here as we make progress on that.

**Comment by fabiocav** [comment] 2022-06-01 18:41
@fabio-marini as this has the same root cause as the issue @kshyju mentioned above, we'll close this and continue to track updates in the other. Please let us know if you have any additional questions.

**Closed by fabiocav** 2022-06-01 18:41 UTC
Labels: Needs: Triage (Functions)
