### ISSUE TITLE
Azure function Isolated mode completing the service bus messages even if middleware next not called.

### ISSUE THREAD

**Issue by krishnasinghabsg** [Azure/azure-functions-dotnet-worker#997] opened 2022-08-19 17:49 UTC
ServiceBusFuncProcessor:
Tools used: vs2022
New V4 app 

Hi,
Am trying to use middleware feature of azure functions isolated mode.
In middleware am reading from redis list of function names that must be disabled and then only calling middleware next if function name is not found in redis disable list.
Everything is working fine but only one problem. IF function is disabled then middleware next is not executed and even function body is not executed but the message is remove from service bus active queue. Looks like azure function run time calls complete on msg after the middleware execution completes.  How can i stop this. I want the message to remain in active queue if Middleware next() is not fired for that message. Idea here is to achieve realtime disabling of az function(s) based on some value in redis cache.  Below is sample code

```
public class FunctionDisabledMiddleware : IFunctionsWorkerMiddleware
{
    public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
    {
        try
        {
            var cachService = context.InstanceServices.GetService<IMyCache>();
            var disableFuncNames = await cachService.GetAsync<string>("FunctionApp1:keyName");
            var funcNames = disableFuncNames.Split(',');
            if (!funcNames.ToList().Contains(context.FunctionDefinition.Name, StringComparer.OrdinalIgnoreCase))
            {
                await next(context);
            }
            else
            {
                
            }
        }
        catch (Exception ex)
        {
            var log = context.GetLogger<FunctionDisabledMiddleware>();
            log.LogWarning(ex, string.Empty);
        }
    }
}

```

**Comment by kshyju** [comment] 2022-08-23 22:32
As of today, the two potential outcomes of a function execution are

1. Success - The trigger payload is processed successfully.
2. Failure - There was an error/exception while processing the trigger payload. 

In this example, the `FunctionDisabledMiddleware` is not executing the remaining middleware pipeline which processes the invocation. Since there are not exceptions/errors while handling the invocation, the isolated function app sends "Success" as the invocation result status to the host and host will mark the invocation as successful.

There is no built-in support to send a service bus message back to active status in the same queue it came from. If your invocation resulted in Failure status, then depending upon the configuration, the message will be retried again and eventually be sent to the [dead-letter queue](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues).

One other **_hacky workaround_** option you could consider exploring is to process the message in the isolated function and send it to same queue via ServiceBus output binding. I would not be able to comment whether that will be an overkill or not without holistically knowing your full system.

@alrod Could you share your thoughts on this use case?

**Comment by jviau** [comment] 2022-08-24 20:33
@krishnasinghabsg this is an interesting scenario that Azure Functions doesn't natively support. The reason is functions host needs to know about a function being enabled/disabled _before_ we dequeue the message, otherwise we risk repeated dequeues of the same message and then eventual dead-lettering. So dynamic enabling/disabling of functions would be a product enhancement.

However, we can help brainstorm some ways for you to accomplish your goal here. What will really affect what route your solution goes down I think depends on what your _re-enabling_ of the function scenario looks like. The problem is, when a function is disabled you will need to park these messages somewhere for consumption when the function is later enabled. Can you just leverage a delayed message? So if your scenario is disabling for a given time period, the solution could simply submit essentially a copy of the message with a delay for that time period. If your scenario is some non-determinate time period, and manually re-enabling the function, then these messages will need to parked somewhere else while disabled, then enabling involves moving them all back into the original queue for processing.

**Comment by brettsam** [comment] 2022-08-31 18:38
@jviau -- can you create an issue to track this in the azure-functions-host repository?

**Comment by jviau** [comment] 2022-08-31 18:47
Resolving in favor of https://github.com/Azure/azure-functions-host/issues/8691

**Closed by jviau** 2022-08-31 18:47 UTC
Labels: enhancement
