### ISSUE TITLE
dotnet 8 isolated worker does not reload configuration after updating json file

### ISSUE THREAD

**Issue by ben-ward1** [Azure/azure-functions-dotnet-worker#2792] opened 2024-10-21 16:52 UTC
### Description

Posting this here after getting no responses in [this discussion](https://github.com/Azure/azure-functions-dotnet-worker/discussions/2791).

The json configuration provider in a v4 Azure functions w/ dotnet 8 isolated worker does not reload config values when the json file is changed.

The often cited `reloadOnChange: true` option when adding a json file for configuration, as seen below, does not seem to be respected.

```
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureAppConfiguration((hostingContext, config) =>
    {
        config.SetBasePath(Directory.GetCurrentDirectory());

        if (hostingContext.HostingEnvironment.IsDevelopment())
        {
            config.AddJsonFile("local.settings.json", optional: false, reloadOnChange: true);
        }

        config.AddEnvironmentVariables();
    })
    .ConfigureServices((hostingContext, services) =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();

        services.ConfigureAppOptions(hostingContext.Configuration);
    })
    .Build();

host.Run();
```

This prevents IOptionsMonitor/IOptionsSnapshot from returning up-to-date values for json provided configuration.

I looked through the docs to determine if this is an intended/known limitation for the isolated worker process, but never found anything explicit.

### Steps to reproduce

See [this repo](https://github.com/ben-ward1/dotnet-config-reload/tree/main) to reproduce the the current behavior in an azure function app alongside the expected behavior in a web api.

**Comment by jviau** [comment] 2024-11-13 18:08
@ben-ward1 `local.settings.json` is not intended to be loaded through `IConfiguration`. It is loaded by core tools and the values are supplied as environment variables to both the host and worker process.

Beyond that, we do not own `.AddJsonFile` or auto reloading of `IConfiguration`, this issue is better suited for dotnet/runtime repo.

Closing as this is by design for `local.settings.json`.

**Closed by jviau** 2024-11-13 18:08 UTC
Labels: Needs: Triage (Functions), potential-bug

**Comment by ben-ward1** [comment] 2024-12-26 21:15
@jviau 

> If you want config to auto-reload for the worker only, you can use a custom json file (such as `appsettings.json`)

After some experimentation, it seems that auto-reloading from a custom json file does not work out of box in the same way for the isolated worker as it does for a standard web app. For a custom json settings file, configuration will reload if the *published* file rather than the *source* file is changed. To force the auto-reload from source, I found a workaround by explicitly pointing to the source directory when adding the json file ([see here](https://github.com/ben-ward1/dotnet-config-reload/blob/b08f7c6fd6a7eb498c6b79785f06949299fd9c7c/ConfigReload.Function/Program.cs#L17-L18)).

Do you think that this difference between isolated worker vs web app is an issue suited for the dotnet/runtime repo?

Side note, this works just the same whether local.settings.json or a custom file is used ([see here](https://github.com/ben-ward1/dotnet-config-reload/commit/e59d2eccfa366cf3d82f1990cc15b2d0f396a769)).
