### ISSUE TITLE
Support for ASP.NET middleware when using integration

### ISSUE THREAD

**Issue by aj-patterson** [Azure/azure-functions-dotnet-worker#1796] opened 2023-07-31 20:18 UTC
Hi, my team is trying to utilize authorization via Cookie and via JWT Bearer tokens. Doing so in ASP.NET is not difficult, but I'm having significant trouble doing so in an isolated .NET 6 worker. It looks like even with the ASP.NET integration, you can't use an ASP.NET middleware pipeline, at least according to [docs](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration-preview)

Happy to hear workarounds, but I think supporting at least significant middlewares like Authentication and Authorization would be very helpful.

**Comment by jviau** [comment] 2023-08-16 18:46
Duplicate of #1725

**Closed by jviau** 2023-08-16 18:46 UTC
Labels: feature: HTTP types
