### ISSUE TITLE
TimerInfo object shows incorrect Next execution time

### ISSUE THREAD

**Issue by simonholmandev** [Azure/azure-functions-dotnet-worker#2077] opened 2023-11-20 08:15 UTC
The TimerInfo object that comes as the default timer lists the "Next" execution as the current execution. Shouldn't this show the **next** execution that is coming based on the schedule, not the current execution?

Otherwise, should it be named Current rather than Next. The Last shows the previous execution, so I would expect Next to show the upcoming execution.

**Comment by kshyju** [comment] 2023-11-20 23:43
Closing as duplicate of #954 

Please leave a comment on that issue if you have further suggestions to improve our docs/templates. Thank you!

**Closed by kshyju** 2023-11-20 23:43 UTC
