### ISSUE TITLE
E2E tests: EventGrid

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-dotnet-worker#141] opened 2021-02-17 21:55 UTC

**Comment by mattchenderson** [comment] 2024-04-23 15:39
Closing this as a duplicate of https://github.com/Azure/azure-functions-dotnet-worker/issues/1607 (This issue came much earlier, but the other has a bit more detail and is in a better place to track this going forward)

**Closed by mattchenderson** 2024-04-23 15:39 UTC
Labels: area: test
