### ISSUE TITLE
Port configuration from local.settings.json not respected in dotnet-isolated mode

### ISSUE THREAD

**Issue by jp1482** [Azure/azure-functions-dotnet-worker#745] opened 2021-12-08 16:04 UTC
Software Configuration
- Visual Studio 2022 
- .NET 6

Azure Functions Version : 4
Runtime : dotnet-isolated

There is host configuration is local.setting.json 

```
"Host":{
   "CORS":"*",
   "LocalHttpPort":7073
}
```

Now if I run function with httptrigger using F5  of Visual Studio , it is still running on 7071. Also when I remove CORS then it create problem. It means that configuration read but port setting not applied when running. If I run from commandline func start then it run on 7073 so why it is not running when I direct run from Visual Studio.

**Comment by anthonychu** [comment] 2021-12-14 22:09
Closing as duplicate of https://github.com/Azure/azure-functions-core-tools/issues/823

**Closed by anthonychu** 2021-12-14 22:09 UTC
Labels: Needs: Triage (Functions)
