### ISSUE TITLE
Bindings does not pass Tuple input parameters

### ISSUE THREAD

**Issue by andsj073** [Azure/azure-functions-dotnet-worker#1219] opened 2022-12-08 10:00 UTC
Hello
Using Net7.0 and AzureFunctions v4 the following type of Function declaration does not work as expected runtime. tuple.Item1 and tuple.Item2 are both null in the body of the function.
(This worked fine on Net6 in-process)
Sending one of the tuple items individually works fine. It is when coupling them in a Tuple that doesn't.

    [Function(nameof(SendMsgToDynamicQueue))]
    [ServiceBusOutput("{tuple.Item1.QueueName}", Connection = "CONNECTION_PREFIX")] 
    public static string SendMsgToDynamicQueue(
        [ActivityTrigger] Tuple<string, MetaDataMessage> tuple, 
        FunctionContext executionContext)
    { }

            await orchestrationContext.CallActivityAsync<string>(
                nameof(SendMsgToDynamicQueue), 
                (msgpayload, metadata));

**Comment by markheath** [comment] 2022-12-08 10:55
I've just run into the same issue, with .NET 6, converting a function app to isolated functions v4 and passing ValueTuple parameters to an Activity function no longer works

**Comment by jviau** [comment] 2022-12-14 19:51
Duplicate of #1218

(They are both serialization issues).

**Comment by jviau** [comment] 2022-12-14 19:59
In-proc and out-of-proc use different default JSON serialization libraries (`Newtonsoft.Json` and `System.Text.Json` respectively). STJ may not support deserialization of `Tuple`.

Also, this line `(msgpayload, metadata)` is a _ValueTuple_, which is different from a _Tuple_. https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples#tuples-vs-systemtuple

**Comment by ben-hamida** [comment] 2023-03-12 22:18
I tried serializing and deserializing a value tuple with System.Text.Json and have confirmed that it doesn't work.

A workaround is to configure the function app to use Newtonsoft.Json as seen in this [sample](https://github.com/Azure/azure-functions-dotnet-worker/blob/ec518944144a4bccdc5ea1e0695d9d6b582bc084/samples/Configuration/Program.cs#L66)

**Closed** 2023-03-20 04:01 UTC
Labels: question, Needs: Author Feedback, no recent activity
