### ISSUE TITLE
Functions not found in Azure after nuget update

### ISSUE THREAD

**Issue by Rtalos** [Azure/azure-functions-dotnet-worker#2070] opened 2023-11-16 09:02 UTC
Hello,

We are experiencing an issue where no functions are found. This happens when deployed to Azure using the latest nuget of: Microsoft.Azure.Functions.Worker.Sdk v 1.16.0, 1.16.1 and 1.16.2.

It is worth to note that this works locally, on all versions, when running from Visual Studio 2022.

Noteworthy information:

- Azure West Europe
- ASEv3
- OS: Windows
- Runtime v: 4.27.5.21549
- Runtime stack: .Net - V6.0
- SKU/size: IsolatedV2 I1v2

In azure portal we can see that there are no function.
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/19684631/2b451042-801e-4c0a-9655-962e328143d0)

I have downloaded the app content from Azure and can confirm that the function dll is present.

What works:

- Rolling back to 1.15.1
- Running 1.16.x with ``` <FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing> ```

**Comment by cr3wdayt5p** [comment] 2023-11-16 10:55
As in https://github.com/Azure/azure-functions-dotnet-worker/issues/2063 I can confirm that we have the same issue but with other Function App hosting details:
 - Azure North Europe 
 - App Service plan
 - Linux
 - PremiumV3
 - Stack: `DOTNET-ISOLATED|7.0`
 - Runtime version: 4.27.5.5

**Comment by ludwhe** [comment] 2023-11-16 11:02
Copying technical information from my comment in the other issue as the same problem occurs on Azure China :
- EP plan
- Windows
- Stack: `DOTNET-ISOLATED|7.0`
- Runtime version: 4.27.5.21549

Works in West Europe, breaks in China East 2.

**Comment by kshyju** [comment] 2023-11-16 16:57
@Rtalos I could not repro this in the exact same environment you shared. If you can share information about your app, we will take a closer look to understand what is going on.  See how to [Share your Function app name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by kshyju** [comment] 2023-11-16 18:24
@cr3wdayt5p I could not reproduce this issue in the exact same environment you shared. If you can share information about your app, we will take a closer look to understand what is going on.  See how to [Share your Function app name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by cr3wdayt5p** [comment] 2023-11-16 18:47
> @cr3wdayt5p I could not reproduce this issue in the exact same environment you shared. If you can share information about your app, we will take a closer look to understand what is going on. See how to [Share your Function app name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

Thank you for trying. I just tested again, and it is still reproducible today.

Using option 2:
North Europe
2023-11-16 18:43:09Z
420c3590-9611-4597-b3ac-b1212a3582c1

**Comment by aolszowka** [comment] 2023-11-16 20:27
Confirm that we are seeing this issue as well in our environments. The work around of `<FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing>` is working and we're redeploying to all of our environments.

Here is our App Hosting Details

* Azure North Central US
* OS Windows
* SKU P1v2
* Runtime: 4.27.5.21549
* Stack: .NET - v6.0

I believe this is the root cause of the issue https://github.com/Azure/azure-functions-dotnet-worker/pull/1968#issuecomment-1787998486

@kshyju
2023-10-24T13:46:22.2923249+00:00
34278435-7031-44b9-9cde-1cbb40d2843b
North Central US

**Comment by ChristopherL-STCU** [comment] 2023-11-16 20:34
Same issue

Using option2:
West US 2
2023-11-16T20:33:01Z
36fe553b-1103-4522-8cb0-bea89ce5712d

**Comment by Rtalos** [comment] 2023-11-16 20:39
> @Rtalos I could not repro this in the exact same environment you shared. If you can share information about your app, we will take a closer look to understand what is going on. See how to [Share your Function app name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

Thank you for looking in to this. 

Here is the info, hope I did everything right:
West Europe
2023-11-16T20:34:22.850Z
af5c7a37-a8a8-4231-a381-0052101824fe\

**Comment by kshyju** [comment] 2023-11-17 19:07
If you are experiencing the "**_No job functions found_**" error when using [Microsoft.Azure.Functions.Worker.Sdk 1.16.X](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.2) and your function app is running on an app service environment, add the below app setting to your app and that will fix the issue.

Name: `AzureWebJobsFeatureFlags`
Value: `EnableWorkerIndexing`

The next version of host update will have this app setting baked into it.

If you are experiencing an issue on another platform, please open a new issue with details specific to your issue.

**Comment by cr3wdayt5p** [comment] 2023-11-18 12:20
@kshyju Great news that you have located the issue with this breaking change 👍

Two follow up questions:
1. How can we check that the hosts we use have been updated to support `1.61.x`? I.e.:
    - If on `1.15.1` when can we safely upgrade to `1.16.x` without needing to set the feature flag?
    - If on `1.16.2` with feature flag – when can we remove this temporary feature flag?
2. How do you intent to prevent something like this happening in the future? On the surface it seems a little crazy that you would deploy a breaking change version of `Worker.Sdk` to NuGet before ensuring that ALL Azure Function hosts worldwide have been updated to support the breaking change.

**Comment by Rtalos** [comment] 2023-11-18 20:49
> If you are experiencing the "**_No job functions found_**" error when using [Microsoft.Azure.Functions.Worker.Sdk 1.16.X](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.2) and your function app is running on an app service environment, add the below app setting to your app and that will fix the issue.
> 
> Name: `AzureWebJobsFeatureFlags` Value: `EnableWorkerIndexing`
> 
> The next version of host update will have this app setting baked into it.
> 
> If you are experiencing an issue on another platform, please open a new issue with details specific to your issue.

Thank you for the response.

The workaround indeed seems to solve the issue; however we would rather wait for the update.

Is there any ETA on this update?

**Comment by fabiocav** [comment] 2023-11-21 01:30
@Rtalos we're actively working on enabling this for ASEs. We'll provide an update here when that is done, but in the meantime, the workaround provided by @kshyju would be a solution if trying to run on the latest SDK versions. 

Thank you for sharing the details and for the patience here!

**Comment by well0549** [comment] 2023-11-27 18:07
See the same issue with
.Net Isolated
.Net Framework 4.81
I get an internal server error.
Would like to know when it's solved.

**Comment by JasonWilby6** [comment] 2023-11-27 21:31
We have the same problem with Function Apps not loading their functions in Azure

There is obviously a breaking change in **Microsoft.Azure.Functions.Worker.Sdk** version 1.16.x onwards

It fails at v1.16.2 but if I make a single change back to version 1.15.1 it bursts into life.

Can someone explain the breaking change at 1.16.x so that we can update without breaking our Function Apps ?

**Comment by aolszowka** [comment] 2023-11-27 21:52
@JasonWilby6 Does https://github.com/Azure/azure-functions-dotnet-worker/issues/2070#issuecomment-1816945300 not solve the issue for you?

**Comment by JasonWilby6** [comment] 2023-11-28 12:54
No setting that flag did not fix the issue introduced at Microsoft.Azure.Functions.Worker.Sdk v1.16.x

Setting is in place on our Function App temp-connexon-dact-fa/slots/deployment

Failure to load functions at v1.16.2 remains the same even with that setting in place.

Functions Host Log still reports functions are present, found but not loaded

2023-11-28T12:45:50.605 [Information] Reading functions metadata (Custom)
2023-11-28T12:45:50.605 [Information] 1 functions found (Custom)
2023-11-28T12:45:50.605 [Information] 0 functions loaded
2023-11-28T12:45:50.605 [Information] Loading functions metadata
2023-11-28T12:45:50.610 [Information] Reading functions metadata (Custom)
2023-11-28T12:45:50.610 [Information] 1 functions found (Custom)
2023-11-28T12:45:50.610 [Information] 0 functions loaded
2023-11-28T12:46:02.876 [Information] Loading functions metadata
2023-11-28T12:46:02.881 [Information] Reading functions metadata (Custom)
2023-11-28T12:46:02.882 [Information] 1 functions found (Custom)
2023-11-28T12:46:02.882 [Information] 0 functions loaded
2023-11-28T12:46:02.882 [Information] Loading functions metadata
2023-11-28T12:46:02.891 [Information] Reading functions metadata (Custom)
2023-11-28T12:46:02.891 [Information] 1 functions found (Custom)
2023-11-28T12:46:02.891 [Information] 0 functions loaded

Simply switching back to Microsoft.Azure.Functions.Worker.Sdk v1.15.1 and the functions are loaded without any other changes to anything else.

                       Jason

**Comment by JustinBerger** [comment] 2023-12-02 00:27
Ran into this error running in visual studio.
1.15.1 works without any local.settings.json file.
1.16.1-3 fails without any local.settings.json file.
Add local.setting.json file with specific values mentioned in #2107 and it works again.

**Comment by JasonWilby6** [comment] 2023-12-03 17:23
1.16.2 works perfectly locally running in Visual Studio (so nothing needs changing in the local.settings.json since locally its running fine)

I added "AzureWebJobsFeatureFlags": "EnableWorkerIndexing" to the local.settings.json but as expected it made no difference (still works locally but still fails to load functions in Azure)

Clearly a breaking change has been introduced at 1.16.x making it fail to load functions when running in Azure (just changing the 1.16.x back to 1.15.1 and everything works perfectly in Azure)

                           Jason

**Comment by cr3wdayt5p** [comment] 2023-12-15 09:30
I just tested again, and it appears to be working now.

My Azure App Service Function host now reports:
Runtime version: 4.28.3.3

And it works with both version `1.6.2` and `1.6.4` without having to explicitly set any flags.

**Comment by fizch** [comment] 2023-12-28 01:20
I am having this issue in my local environment. I can reproduce it by using the func CLI to create a new function that is dotnet-isolated using c# isolated and using the timer trigger template. If I run it with the default packages, it works fine, but as soon as I update Microsoft.Azure.Functions.Worker.Sdk to 1.16.0 and above, it fails to find a function.

Environment details:

- OS - Win 11 Pro
- Core Tools Version - 4.0.5312
- Function Runtime Version - 4.23.2.21220
- Visual Studio Version - 17.8.3

**Comment by frasermclean** [comment] 2024-01-04 04:05
I am experiencing this issue when running on a Windows consumption plan. 
```
2024-01-04T04:03:43.116 [Information] Loading functions metadata
2024-01-04T04:03:43.119 [Information] Reading functions metadata (Custom)
2024-01-04T04:03:43.119 [Information] 1 functions found (Custom)
2024-01-04T04:03:43.119 [Information] 0 functions loaded
2024-01-04T04:03:43.121 [Information] Loading functions metadata
2024-01-04T04:03:43.122 [Information] Reading functions metadata (Custom)
2024-01-04T04:03:43.122 [Information] 1 functions found (Custom)
```

Downgrading to `Microsoft.Azure.Functions.Worker.Sdk` version `1.15.1` seems to make everything again.

**Comment by JasonWilby6** [comment] 2024-01-04 09:01
Yes. This works perfectly at v1.15.1 but doing nothing except upgrading to v1.16.x causes the functions to no longer load.

Just updating from v1.15.1 to v1.16.x (with absolutely no other changes) causes a function loading failure !

Clearly Microsoft have introduced a bug at v1.16.x and now need to indicate how to get around their bug.

**Comment by fabiocav** [comment] 2024-01-09 00:56
@JasonWilby6 @frasermclean can you confirm whether you're seeing that locally or hosted? 

If local in VS ( @fizch , this would apply to you), can you please try the following to ensure you're using the latest tools:

`Tools > Options > Projects and Solutions > Azure Functions > Check for updates` and download/install updates if available (@fizch this should be the case for you as you're running on pretty old versions).

@Rtalos (and anyone experiencing this on ASE), can you please open a support ticket to ensure your environment is properly updated? This would be the quickest way to get this addressed.

Thanks!

**Comment by frasermclean** [comment] 2024-01-09 01:15
@fabiocav No, this doesn't happen locally. I can use the latest packages and all works fine locally. It's only when I deploy the Function App to Azure that I see the issue. I am running on Windows consumption plan.

**Comment by aolszowka** [comment] 2024-01-09 02:40
@frasermclean / @morrisonbrett I'm as assuming you tried the work around that was mentioned (and I confirmed working in https://github.com/Azure/azure-functions-dotnet-worker/issues/2070#issuecomment-1816945300) note that this is set as an MSBuild variable (within the csproj file) NOT as a setting in the local.settings.json, perhaps that was @JasonWilby6 's issue, I didn't read their response closely enough last time.

**Comment by morrisonbrett** [comment] 2024-01-09 04:53
The problem only exists on Azure. This workaround works as I indicated: https://github.com/Azure/azure-functions-dotnet-worker/issues/2107#issuecomment-1834683963

**Comment by JasonWilby6** [comment] 2024-01-09 08:00
This is Hosted in Azure in an Standard Azure App Service Plan.

Its happening in multiple App Service Plans (S1 and S2).

The Microsoft.Azure.Functions.Worker.Sdk v1.16.x clearly has a breaking change (change just this back to v1.15.x and functions start loading again).

When will Microsoft fix this or explain how to work around their broken v1.16.x ?

**Comment by JasonWilby6** [comment] 2024-01-09 08:05
The setting described in the link makes no difference.

Its happening in multiple App Service Plans (S1 and S2).

The Microsoft.Azure.Functions.Worker.Sdk v1.16.x clearly has a breaking change (change just this back to v1.15.x and functions start loading again).

When will Microsoft fix or explain how to work around their broken v1.16.x ?

**Comment by frasermclean** [comment] 2024-01-09 08:12
Thanks @aolszowka , I added `<FunctionsEnableWorkerIndexing>False</FunctionsEnableWorkerIndexing>` to the `PropertyGroup` within the csproj and redeployed to Azure. Now my functions are getting detected.

Are we any closer to understanding why this makes it work and what the root cause is?

**Comment by Rtalos** [comment] 2024-01-11 12:13
> @JasonWilby6 @frasermclean can you confirm whether you're seeing that locally or hosted?
> 
> If local in VS ( @fizch , this would apply to you), can you please try the following to ensure you're using the latest tools:
> 
> `Tools > Options > Projects and Solutions > Azure Functions > Check for updates` and download/install updates if available (@fizch this should be the case for you as you're running on pretty old versions).
> 
> @Rtalos (and anyone experiencing this on ASE), can you please open a support ticket to ensure your environment is properly updated? This would be the quickest way to get this addressed.
> 
> Thanks!

We have just verified that all our functions are working on 1.16.4 in Azure.

Thank you!

**Comment by JasonWilby6** [comment] 2024-01-11 12:19
The functions are failing to load when HOSTED in Azure in an App Service Plan (multiple instances as SKU "S1" and SKU "S2")

The MS breaking change is in 1.16.x as changing just this back to 1.15.x bursts into life.

When will Microsoft explain how to work around their v1.16 broken code ?

**Comment by fabiocav** [comment] 2024-01-17 21:28
@morrisonbrett , about this:
> IDK why they keep asking people to repro locally. It only happens in a deployed instance on Azure. Haven't we already established that?

We do have evidence of this impacting local experiences as well, and need to make sure we're tracking the different issues so they can be addressed.
From @fizch :
> I am having this issue in my local environment.

**Comment by fizch** [comment] 2024-01-19 03:23
@fabiocav I did get this working by updating my CLI to the current version. Thank you!

**Comment by jaceks2106** [comment] 2024-02-01 09:16
Hi guys, I have been struggling with this problem for last couple days and this workaround with disabling worker indexing seemed to me really wrong. Finally, I found the solution for my problem. The appsetting `"FUNCTIONS_WORKER_RUNTIME":"dotnet-isolated"` was missing on Azure Functions resource. It was set on `local.settings.json`, so locally it worked. But when I removed, the behavior was the same.

**Comment by wc-whiteheadd** [comment] 2024-02-08 15:39
Just thought i would help people out a bit.

I have been hitting a similar issue all day where after an Isolated worker, .net 8 upgrade to our azure functions, they would not longer work/show in Azure. I could see that when deploying it manually via the IDE, it worked fine in Azure but failed/never loaded when doing a normal CICD deployment.

I have now eventually tracked this issue down and thought i would share in case it helps anyone else.

So when moving to the isolated worker process for .NET 8, it turns out they have changed how the release files are now compiled and distributed. They now create a folder named ".azurefunctions" which holds the connecting information for the deployed azure functions upon a release build. Most compression libraries unless strictly supplied, actually exclude folders with "." in their name as its generally reserved for hidden directories. This is most probably why a lot of peoples CICDs are now deploying broken azure functions as the majority of people are doing zip deployments in their CICD.

For reference the original deployment structure was a folder for each azure function with its name with no "." in the name, so upon people upgrading to the new version, their CICDs will be excluding the folders by default from the deployment to Azure.

If you go into "Advance Tools" and navigate to the wwwroot folder you will be able to confirm if this is an issue for yourself as the folder will be missing.

**Comment by soninaren** [comment] 2024-02-18 04:43
Closing this, since the original issue has been resolved. Please open a new issue with all the relevant details if anyone is still running into issues.

**Closed by soninaren** 2024-02-18 04:43 UTC
Labels: Needs: Attention :wave:
