### ISSUE TITLE
ApplicationInsights telemetry doesn't seem to be fully integrated in Visual Studio

### ISSUE THREAD

**Issue by nulltoken** [Azure/azure-functions-dotnet-worker#1282] opened 2023-01-20 12:34 UTC
:wave: Hello, when configuring an azure function as described in https://github.com/Azure/azure-functions-dotnet-worker/issues/1182#issuecomment-1317230604, raw telemetry data is indeed displayed in the VisualStudio output window.

However, it doesn't show up in the integrated ApplicationInsights viewer integrated in Visual Studio (cf. https://learn.microsoft.com/en-us/azure/azure-monitor/app/visual-studio#application-insights-search).

Am I missing something obvious or is this integration still missing?

**Comment by fabiocav** [comment] 2023-02-01 19:10
Thanks for raising this, @nulltoken

We'll take a closer look to better understand what is happening here and provide an update when we have information.

**Comment by fabiocav** [comment] 2023-02-01 19:11
@nulltoken can you share a repro and/or the steps you're following to test this?

**Comment by nulltoken** [comment] 2023-02-05 13:41
@fabiocav Thanks for the answer. 

I'll prepare a quick repro repository in the following days and will ping back.

**Comment by nulltoken** [comment] 2023-02-06 07:56
@fabiocav Here you are.

- Clone https://github.com/nulltoken/azure-functions-dotnet-worker-issue-1282
- Open the solution
- Run F5
- Navigate to http://localhost:7159/api/StartHelloCitiesUntyped
- Open up "Application Insights Search" window from within VS

This is what I see
![image](https://user-images.githubusercontent.com/92363/216915580-15bb3721-7a8a-40fe-80ef-c844578feca0.png)

**Note:** this repro also includes an external http call

**Comment by magols** [comment] 2023-03-23 17:00
I have this same issue. Functions .NET 7, isolated mode. Application Insights data is sent from local machine to the ingester and is visible in the Azure portal. But the "local debug session" in the Application Insights Search panel in Visual Studio does not pick up anything and is always empty.

**Comment by jviau** [comment] 2023-06-21 21:15
Duplicate of #439

**Closed by jviau** 2023-06-21 21:15 UTC
Labels: needs-investigation, logging, application-insights
