### ISSUE TITLE
SB Message delivery pauses on with session enabled queues and wide session id spaces

### ISSUE THREAD

**Issue by pcolemannxu** [Azure/azure-functions-dotnet-worker#831] opened 2022-03-17 20:44 UTC
I have a very basic handler that receives messages from a session enabled queue. There is nothing except version 2.0 in the `hosts.json` file. This is running on .net6, function version 4, and I get the same results running locally or deployed in an Azure function.

`     [Function("DotNetIsolatedSessionsIssueTestQueue")]
     public async Task DotNetIsolatedSessionsIssueTestQueue(
         [ServiceBusTrigger("test1", Connection = "ServiceBusConnection", IsSessionsEnabled = true)] byte[] message,
         FunctionContext context)
     {
         await Task.CompletedTask;
     }`

Assume the queue has an endless supply of messages queued. If I use the same session id for all messages that I queue, or use a small set of sessions ids (3 unique ones in total for example) then the messages are received as expected. However if all the session ids are unique in the queue then a batch of messages are received, then the receiver 'stalls' for about a minute before starting up again. Here is some of the output where you can see a minute delay between the first batch that's processed and the last. Obviously this handler does nothing so the time isn't being spent in the handler and processing for each individual messages completes quickly.

![image](https://user-images.githubusercontent.com/47121622/158891457-42e5229c-60fe-498c-896b-3dc7fd4c6ac6.png)

This shows 3 'batches': the last few messages relating to the end of the first batch, all the messages for the 2nd batch, and the first few messages for the 3rd batch. I've tried to highlight the 1-minute stall between batches. The queue had thousands of messages in it so the receiver wasn't waiting for messages to arrive in the queue.

Here are the important bits from the .csproj file:
`  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.0.0-beta.6" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.7.0-preview1" />
  </ItemGroup>`

Are there some V4 settings changing this behavior? I didn't see this prior to upgrading to V4/.net6 isolated.

**Comment by fabiocav** [comment] 2022-03-22 21:31
@pcolemannxu I wouldn't expect the consumer to pause here between sessions. If there's a session available (i.e., not owned by a different instance), the listener should grab the next available one. 

We'll flag this for investigation.

**Comment by pcolemannxu** [comment] 2022-03-23 02:19
@fabiocav here's a solution which reproduces this behavior.

[dotnet-isolated-session-enabled-issue-support.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/8329162/dotnet-isolated-session-enabled-issue-support.zip)

**Comment by fabiocav** [comment] 2022-03-30 20:32
@satvu  and @kshyju will drive this from the worker side, but @alrod is performing the initial investigation for the trigger.

**Comment by satvu** [comment] 2022-04-01 20:56
Updating w/ investigation from @alrod:
This behavior is by design. We have different default values and [schema](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fazure-functions%2Ffunctions-bindings-service-bus%3Ftabs%3Din-process%252Cextensionv5%252Cextensionv3%26pivots%3Dprogramming-language-csharp%23hostjson-settings&data=04%7C01%7Csarahvu%40microsoft.com%7C448786d3bfb84a77507908da12d393c1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637842997487331287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GaYInL%2BPf3NB4Bt27dZKMEvdOL3d3mwrJCVRl%2BwIjWY%3D&reserved=0) for maxConcurrentSessions for 2.x+  and 5.x+:

V4=2000
V5=8

[https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Config/ServiceBusOptions.cs#L123](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fblob%2Fmain%2Fsdk%2Fservicebus%2FMicrosoft.Azure.WebJobs.Extensions.ServiceBus%2Fsrc%2FConfig%2FServiceBusOptions.cs%23L123&data=04%7C01%7Csarahvu%40microsoft.com%7C448786d3bfb84a77507908da12d393c1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637842997487331287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xMmI5cPtO3x%2BKZPjkgdHyiuIM3tqJakNNBPfOSMVbkg%3D&reserved=0)

Lock sessions time default is the same = 1 minute (2.x+ – messageWaitTimeout, 5.x+ - sessionIdleTimeout)

Closing since this is expected behavior.

**Closed by satvu** 2022-04-01 20:56 UTC
Labels: needs-investigation
