### ISSUE TITLE
Custom telemetry properties are not logged in .net 7 v4 function app

### ISSUE THREAD

**Issue by sarreddy007** [Azure/azure-functions-dotnet-worker#1471] opened 2023-04-16 07:21 UTC
We have recently migrated from .netcore 3.1 v3 to .net 7 v4 function app. I see a change in the telemetry behavior as the custom properties are not being logged. 

netcore 3.1 app has Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger which used to log the RequestTelemetry with custom properties if an initializer is attached. 

Is this a existing issue in .net7 v4 function app?

**Comment by xin9le** [comment] 2023-05-24 14:47
I have also encountered the same issue. I believe that #1292 and #1312 are probably related.

At this point, I can't and don't wish to revert the implementation back to InProc. However, I would like to be able to modify the custom properties on `RequestTelemetry`.

It seems that all we can do for now is patiently await improvements in functionality.

**Comment by jviau** [comment] 2023-06-21 21:58
This is expected behavior. In dotnet isolated you are now in a separate process and your `ITelemetryInitializer` no longer runs in the host process and has no opportunity to modify that telemetry. We will not be able to address this in the isolated model.

Closing this as "by design"

**Closed by jviau** 2023-06-21 21:58 UTC
Labels: question, application-insights
