### ISSUE TITLE
Log messages with Level below Information are never logged with default config.

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#573] opened 2021-08-12 09:51 UTC
Here's my startup code:

```
private static Task Main() =>
    new HostBuilder()
        .ConfigureFunctionsWorkerDefaults()
        .ConfigureServices(Startup.ConfigureServices)
        .Build()
        .RunAsync();
```

with this one LogLevels below Information are never logged, no matter what logLevels I set in host.json.
I've found that this might be worked around by adding an explicit SetMinimumLevel call:

```
private static Task Main() =>
    new HostBuilder()
        .ConfigureFunctionsWorkerDefaults()
        .ConfigureLogging(c => c.SetMinimumLevel(LogLevel.Trace))
        .ConfigureServices(Startup.ConfigureServices)
        .Build()
        .RunAsync();
```

I think this is a bug (and one which cost me quite a lot of time).

**Comment by kaotoby** [comment] 2021-08-16 06:14
Can confirm this bug on version 1.3.0 and 1.4.0 too.
#417 is not fixed. Can be reproduced using method described in #417 .

**Comment by timbussmann** [comment] 2021-08-20 11:07
I'm running into the same issues, see this simple repro project here trying to configure debug level logging in `hosts.json`: https://github.com/timbussmann/IsolatedWorkerLoggingRepro

**Comment by Romfos** [comment] 2021-11-12 17:53
Hi, 

@fabiocav, could you please pay attention on this isssue, because now is not possible to see logs in prod for loglevel below information. It makes impossible to investigate prod issues.

My scenario:
1) enable logsi via env variable AzureFunctionsJobHost__logging__LogLevel__Default = Trace

Expected result:
I should be able to see trace logs from application

Actual result:
I'm abel to see logs with 'Trace' label for host, but not trace logs from my application

Thank you

**Comment by heinrich-ulbricht** [comment] 2022-01-19 10:03
It took me multiple hours of tinkering to realize that whatever I configure in `host.json` and however compliant I am with the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-log-levels) - **it just does not work**.

No log level below Information is ever showing up in the Streaming Logs (nor on my local machine). There is always a minimum log level of `Information` set for any logger. And then I found #417 and then this issue here.

I can reproduce this with any new function project I create in Visual Studio Code. All I add to it is `_logger.LogDebug` and `_logger.LogTrace` (to test logging) as well as the `host.json` configuration that should make those log output appear:

```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        },
        "consoleLevel": "verbose",
        "fileLoggingMode": "always",
        "logLevel": {
            "Company.Function.TimerTrigger1": "Trace",
            "default": "Trace",
            "Function": "Trace",
            "Function.TimerTrigger1": "Trace",
            "Function.TimerTrigger1.User": "Trace",
            "Host.Aggregator": "Trace",
            "Host.Results": "Trace"
        }
    }
}
```

All to no avail.

My settings are:
* v4 function runtime
* .NET 6 (Isolated)
* dotnet-isolated
* tried Linux- and Windows-based app service plans, no difference
* tried the function core tools on Linux and Windows, no difference

The solution to get my Debug and Trace messages to finally show up in the Streaming File System Log in Azure I explicitly need to add one line of code:

```
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureLogging(c => { c.SetMinimumLevel(LogLevel.Trace); }) // <======== THIS MAKES DEBUG AND TRACE LOG MESSAGES APPEAR =========
                .Build();

            host.Run();
        }
```

But shouldn't the `host.json` config take care of that?

**Comment by brettsam** [comment] 2023-08-23 20:44
Going to close this in favor of https://github.com/Azure/azure-functions-dotnet-worker/issues/1125. I've given some in-depth explanations of this in various places and will keep that issue updated with links to those comments

**Comment by brettsam** [comment] 2023-08-23 20:45
It's actually technically a dupe -- so closing as dupe

**Closed by brettsam** 2023-08-23 20:45 UTC
Labels: needs-discussion
