### ISSUE TITLE
Unable to publish an Isolated Azure Function

### ISSUE THREAD

**Issue by baronfel** [Azure/azure-functions-dotnet-worker#1834] opened 2023-08-16 21:00 UTC
This is related to https://github.com/dotnet/sdk/issues/30321

An internal team (represented by @gangaken here) is publishing an Isolated Azure Function and experiencing problems during the publish. I can't upload full details here, but Gangadhar and myself are both available on Teams internally.

The main symptom of the failure is that during the publish of their single functions app, the publish of the 'internal' WorkerExtensions.csproj project fails during the `_GenerateFunctionsAndCopyContentFiles` target while `Move`ing  the runtime assets of the WorkerExtensions project to the `publishout/bin` directory. According to the binlog, all of the contents of the `publishout/bin` directory are DoubleWrites - this to me points to a potential source of the problem. Looking at the binlog for one of these DoubleWrite files (for example System.Security.Cryptography.ProtectedData.dll), I see two copies:

* One during the `_CopyResolveDFilesToPublishPreserverNewest` Task from the .NET SDK, whose role is to copy publishable outputs to the publish directory
* One during the `_GenerateFunctionsAndCopyContentFiles` Task from this project.

That's about as far as I've gotten.

**Comment by jviau** [comment] 2023-08-22 21:29
I believe a workaround for this is to build, then publish with `--no-build`.

**Comment by phillipmunn** [comment] 2023-09-29 09:17
@jviau when I try using your workaround by adding `--no-build,` that gives a new error. 

`C:\Program Files\dotnet\sdk\8.0.100-rc.2.23467.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(290,5): error MSB3030: Could not copy the file "C:\OpsyteAgent\_work\2\s\Opsyte.Functions\bin\Release\net7.0\Opsyte.Functions.runtimeconfig.json" because it was not found. [C:\OpsyteAgent\_work\2\s\Opsyte.Functions\Opsyte.Functions.csproj]`

Adding this to the .csproj. Doesn't have any effect either. Any suggestions? 
`<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>`

**Comment by AbhishekTripathi** [comment] 2023-09-29 11:01
> I believe a workaround for this is to build, then publish with `--no-build`.

It is not a solution. We have separate steps but still facing this issue.

In our scenario, we do a build first with ``` dotnet build -c Release --no-restore ./abc.Service.sln -p:Version=05.01.02.65461 ``` and then do ``` dotnet publish --no-restore --no-build -c Release -o ./OutputPackage -p:Version=05.01.02.65461 abc.Service.sln ```

We keep getting errors for different binaries.
> C:\Users\xxx\.nuget\packages\microsoft.net.sdk.functions\3.1.2\build\Microsoft.NET.Sdk.Functions.Publish.targets(144,5): error MSB3677: Unable to move file "F:\ws\nxxx_Jenkins@2\nws\root\component\OutputPackage\Microsoft.Extensions.Hosting.Abstractions.dll" to "F:\ws\nxxx_Jenkins@2\nws\root\component\OutputPackage\bin\Microsoft.Extensions.Hosting.Abstractions.dll". Cannot create a file when that file already exists. [F:\ws\nxxx_Jenkins@2\nws\root\component\someService\someService.csproj]

**Comment by jviau** [comment] 2023-10-05 20:07
I have a preview package published: https://dev.azure.com/azfunc/Azure%20Functions/_artifacts/feed/AzureFunctionsTempStaging/NuGet/Microsoft.Azure.Functions.Worker.Sdk/overview/1.16.0-preview1

Please try this out and see if it addresses your issue and report back

**Comment by phillipmunn** [comment] 2023-10-11 10:27
Hey @jviau.

I've taken our solution and added a reference to this private feed.
I've then updated the Microsoft.Azure.Functions.Worker.Sdk package to both [1.16.0-preview1] or the newly published package [1.16.0-preview2] which has since appeared there.

When we do a full clean and restore there are new error messages in the output window now complain that .NET Core 3.0 is not installed. I don't think we should be installing .NET Core 3.0 given it's out of date.

We're currently just retriggering all the failing builds of our isolated functions app in our pipeline(s) repeatedly until we "get lucky" and a build works.

**Comment by jviau** [comment] 2023-10-11 16:48
Can you share the error message you get regarding netcore3.0 not being installed?

**Comment by phillipmunn** [comment] 2023-10-12 08:40
@jviau I cannot reproduce the error I got earlier now - however I swear I wasn't going mad! It appears to work. Will report back if we see any build failures using this preview package.

**Comment by caminero5000** [comment] 2023-10-13 03:20
@jviau Any idea on when your fix will make it to a stable release ?

**Comment by rajeevranjan21** [comment] 2023-12-11 15:59
Hello Jacob. Is there any fix for this issue ?

**Comment by jviau** [comment] 2024-01-18 21:15
The SDK changes have been merged in. Will be preparing a preview release soon.

**Closed by jviau** 2024-01-18 21:15 UTC
Labels: needs-investigation, SDK

**Comment by jviau** [comment] 2024-01-22 18:39
Fix released: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.0-preview1

**Comment by davidpetric** [comment] 2024-02-07 13:08
> Fix released: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.0-preview1

Finally, thank you!!!

**Comment by magarma** [comment] 2024-03-15 15:53
I see that in version 1.17.2 this changes were reverted... 
Is that PR causing a collateral issue or something?
What is the best way to avoid this issue? I'm facing the same one

**Comment by jviau** [comment] 2024-03-18 17:35
@magarma yes the changes included a regression. This PR adds it back in: #2347

**Comment by TiagoAntunesALS** [comment] 2024-04-16 17:56
We are having the same issue with Microsoft.Azure.Functions.Worker.Sdk 1.17.2, the 1.17.3-preview1 is working as expected

**Comment by johnsharp1975** [comment] 2024-10-03 10:06
I've started receiving this message over the last few weeks. There have been a couple of instances before today but today's really bad, I'm not getting less than 10% successful pipeline runs. An example from today has been:

##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\microsoft.net.sdk.functions\4.3.0\build\Microsoft.NET.Sdk.Functions.Publish.targets(144,5): Error MSB3677: Unable to move file "C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\rvel1jgu.jtv\publishout\Microsoft.AspNetCore.Authorization.dll" to "C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\rvel1jgu.jtv\publishout\bin\Microsoft.AspNetCore.Authorization.dll". Cannot create a file when that file already exists.
