### ISSUE TITLE
Sometime azure functions don't work

### ISSUE THREAD

**Issue by Romfos** [Azure/azure-functions-dotnet-worker#346] opened 2021-03-23 11:51 UTC
Hello, I have following problem:

I have logs about beginning of execution of operation and timeout issue at the end, but without any logs in between:

2021-03-23T11:40:16.062 [Information] Executing 'Functions.AccountMappingImporter' (Reason='This function was programmatically called via the host APIs.', Id=1689540d-e2a6-46d3-b9b6-56b2ac84330b)
2021-03-23T11:40:16.074 [Trace] Sending invocation id:1689540d-e2a6-46d3-b9b6-56b2ac84330b
2021-03-23T11:40:16.074 [Trace] Posting invocation id:1689540d-e2a6-46d3-b9b6-56b2ac84330b on workerId:fcaea856-ff5b-4c30-92b6-7b778eae17e9
2021-03-23T11:45:16.112 [Error] Timeout value of 00:05:00 exceeded by function 'Functions.AccountMappingImporter' (Id: '1689540d-e2a6-46d3-b9b6-56b2ac84330b'). Initiating cancellation.
2021-03-23T11:45:16.241 [Error] Executed 'Functions.AccountMappingImporter' (Failed, Id=1689540d-e2a6-46d3-b9b6-56b2ac84330b, Duration=301188ms)Timeout value of 00:05:00 was exceeded by function: Functions.AccountMappingImporter
2021-03-23T11:45:18.317 [Warning] A function timeout has occurred. Restarting worker process executing invocationId '1689540d-e2a6-46d3-b9b6-56b2ac84330b'.

Locally all works as exepected, but not after deploy to azure.

Could you please provide me a guide - how can I investirgate such kind of issues?

**Comment by Romfos** [comment] 2021-03-23 12:24
I have following middleware:

    public class TestFunctionsWorkerMiddleware : IFunctionsWorkerMiddleware
    {
        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
            var logger = context.GetLogger("debugs");

            try
            {
                logger.LogInformation("Before " + context.InvocationId);
                await next(context);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error for " + context.InvocationId);
            }
            finally
            {
                logger.LogInformation("After " + context.InvocationId);
            }
        }
    }

and I don't  see "Before" message in logs

**Comment by fabiocav** [comment] 2021-03-23 16:24
@Romfos what logs are you looking at? Can you please share your function app name so we can take a closer look? Thanks

**Comment by Romfos** [comment] 2021-03-23 16:51
@fabiocav 
app name: kaseya1-functions-app-csi-qa
could you please verify logs for 1689540d-e2a6-46d3-b9b6-56b2ac84330b InvocationId?

Thank you!

**Comment by Romfos** [comment] 2021-03-24 13:11
Sometime i see following logs:

```
Microsoft.Azure.WebJobs.Host.FunctionTimeoutException:
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryHandleTimeoutAsync>d__29.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 633)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeWithTimeoutAsync>d__27.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 549)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 505)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__20.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 283)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__20.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 330)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__15.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 94)
```

```
    public class HealthCheckerFunction
    {
        [Function("HealthCheckerFunction")]
        public HttpResponseData HealthCheckerFunctionAsync(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestData request)
        {
            return request.CreateResponse(HttpStatusCode.OK);
        }
    }
```

**Comment by fabiocav** [comment] 2021-03-24 17:01
@Romfos I took a closer look at the app you've shared and it looks like this is an app that is configured for (and using) .NET in-proc. Are you trying to mix in and out-of-proc in the same app? 

The runtime configuration would need to be set to `dotnet-isolated`, but if that is done, your in-proc functions will no longer run, as you can't mix those two modes.

**Comment by Romfos** [comment] 2021-03-24 17:33
@fabiocav No, it was dotnet-isolated, but it had those issues and I decided to rollback to .net core 3.1

**Comment by fabiocav** [comment] 2021-03-24 17:58
Will try to take a closer look at that time frame. Did you have all of those functions there as well? Were they all failing? I see that, even with the .NET in-proc model, there are some timeouts for those functions. Are they expected to take a while?

**Comment by Romfos** [comment] 2021-03-24 18:04
@fabiocav

the latest execution on dotnet-isolated:
![image](https://user-images.githubusercontent.com/12048821/112361404-659aad80-8ce4-11eb-8bfc-5d3da54d3250.png)

now it is green

**Comment by fabiocav** [comment] 2021-04-02 02:17
Sorry, missed your reply here.

Is the app still in the same state? Would you mind triggering another execution so we have some recent data?

/cc @ankitkumarr @brettsam

**Comment by Romfos** [comment] 2021-04-02 10:00
I've checked it yestarday and it still a problem:
![image](https://user-images.githubusercontent.com/12048821/113405933-4b7f6000-93b3-11eb-9916-fdccf13ea50d.png)

Now application restored to .net core 3.1

**Comment by csomers** [comment] 2021-04-28 11:00
We are also seeing this problem with an HTTPTrigger. Having spoken to an MS support engineer, he subsequently sent me an email referencing this issue and advising that we move back to Core 3.1 and suggested: "that you wait for the runtime to mature before moving to that runtime." 
![image](https://user-images.githubusercontent.com/6552121/116393179-36161e00-a819-11eb-8ddf-4af1215cff09.png)

**Comment by Romfos** [comment] 2021-04-28 11:16
@csomers quite strange response from support. Thank you for feedback!

**Comment by Romfos** [comment] 2021-06-14 15:25
@fabiocav 
Hi. 

I can confirm that this issue was fixed after https://github.com/Azure/azure-functions-dotnet-worker/pull/462

Thank you!

@csomers could you please check your issue with this fix?

**Comment by ConroyG** [comment] 2021-07-01 22:43
Hi

I too am getting this exact issue, I had 2 simple functions both using Queue triggers to different azure storage queues and were working fine
I added a 3rd and suddenly everything starts throwing this timeout error (including the older functions that were fine)
![image](https://user-images.githubusercontent.com/4994730/124192748-e48c5700-db19-11eb-966e-168991527710.png)

I've tried the following:
Downgrade to Microsoft.Azure.Functions.Worker 1.2.0
Fully deleted the azure function and recreated (using ARM templates)
Removing code to remove all differences between the new function and older ones (the new function calls the azure maps HTTP API to do some work, none of the older functions used a http client)
Added logs everywhere I can (nothing gets logged from my code)
Deployed older versions (they also seem to have died, slowly going back further to pinpoint the issue)

**Comment by kshyju** [comment] 2022-02-17 02:08
Closing this issue as the original issue posted was fixed, as confirmed by @Romfos

**Closed by kshyju** 2022-02-17 02:08 UTC
Labels: needs-investigation
