### ISSUE TITLE
Unable to use ILogger inside servicebus callback via Azure function (v4 isolated mode).

### ISSUE THREAD

**Issue by gautamsamal** [Azure/azure-functions-dotnet-worker#1129] opened 2022-10-18 12:14 UTC
I am facing trouble with making the logger work inside a service bus handler. It used to work for me on azure function runtime v3 with in-process method. I am now moving my functions to azure function v4 isolated mode but I am not able to make this logger work.

Here is a simple code to reproduce.
**Program.cs**
```
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices((a, b) =>
    {
        // Static keys setup from keyvault
        new Startup().Configure();
    })
    .Build();

host.Run();
```
**Queue Trigger**
```
public TestQueueTrigger(ILoggerFactory loggerFactory)
{
    log = loggerFactory.CreateLogger<TestQueueTrigger>();
}

[Function("TriggerImport")]
public async Task Run([QueueTrigger("test-queue", Connection = "STORAGE_CONNECTION_STRING")] string inputQueueItem, FunctionContext context)
{
    // ...
    MessageSender sender = new MessageSender(SBConnectionString, queueName);
    await sender.SendAsync(message);
    log.LogInformation($"Message added to the service bus"); // Logging

    // Register receiver if not registered. (Need to use singleton object here per queue)
    MessageReceiver receiver = new MessageReceiver(SBConnectionString, queueName, ReceiveMode.ReceiveAndDelete);
    receiver.RegisterMessageHandler(async (message, cancellationToken) =>
    {
        // ...
        log.LogInformation($"Message on queue has been processed."); // Not logging
    },
    new MessageHandlerOptions((e) =>
    {
        log.LogError($"Message on queue failed due to error."); // Not logging
        return Task.CompletedTask;
    })
    { MaxConcurrentCalls = 2 });
}
```

In this function, I am able to see logs that are direct to the scope of the queue trigger and those logs are being pushed into the app insights as well. But the logger outputs within the callback actions are completely missing.

In local system, also doing `func start`, I noticed these logs to be doing nothing. Can anyone help me out of this? Do I need to use external logging service like Serilog? I feel like I am missing something core to dotnet concepts.

Thanks in advance!

**Comment by jviau** [comment] 2022-10-18 16:49
I don't think this is a logger issue, rather I think the handlers on `MessageReceiver` are never invoked. I think the issue is that your function invocation is going to end immediately after constructing `MessageReceiver` and it is going to be garbage collected. You cannot rely on fire & forget work like that on workers in v4 for a couple reasons. 1) this is going to be garbage collected because it goes out of scope soon as the method ends. and 2) even if you kept it in scope, the host does not track this async work and can shut down this worker at any point, leading to unreliable behavior.

**Comment by gautamsamal** [comment] 2022-10-18 16:54
@jviau For simplicity I had abstracted the problem but in our case the receivers are being setup before the `sendAsync`. During the debug or in actual function app, it seems to work reliably so far. It's just the logging that doesn't work anymore. Could be probably because our function app is hosted on an app service plan.

**Comment by gautamsamal** [comment] 2022-10-18 16:56
A custom logger will probably work and I will try that soon. Also open to implement workarounds to achieve the following part, if there is any?

> @kshyju yes, the name of the queue is dynamic here in my case, you can imagine multiple clients/environments. The primary reason why we do this is to limit the concurrent executions based on a client/environment. Thus we are using a service bus with a dynamic queue per client who'll limit the flow of concurrent execution.
> 
> `MaxConcurrentCalls` also can be configured individually. That's the reasoning of using a separate ServiceBus Sdk.

**Comment by jviau** [comment] 2022-10-18 17:08
Can you share the code on how you construct the actual logging in your real-world example?

**Comment by gautamsamal** [comment] 2022-10-18 17:16
@jviau I use the DI and create `ILogger` in the constructor of the Queue Trigger.
```
public TestQueueTrigger(ILoggerFactory loggerFactory)
{
    log = loggerFactory.CreateLogger<TestQueueTrigger>();
}
```
Then I after doing required operations, I send the message to the service bus which is wrapped in a static class. It does accepts the `ILogger` param that is going to be used for the receiver handler.
Something like - 
```
await QueueManagerFactory.Invoke(log).ProcessMessage(message)
```

**Comment by jviau** [comment] 2022-10-18 17:43
I am not sure why the logger does not work for you that way. Have you verified that log statement is being invoked? 

However, in v4 this approach is not recommended - the lifetime of a worker is not guaranteed outside of any active function invocation. Workers may be shutdown by the host at any point. https://learn.microsoft.com/en-us/azure/azure-functions/performance-reliability#make-sure-background-tasks-complete

**Comment by gautamsamal** [comment] 2022-10-18 18:41
thanks. I am not sure either. The handler does execute and process an elaborate flow without logging. I'll checkout other logging options to see if that works.

To be able to run background process, we are using app service plan with "Always On" set. That seems to work perfectly.

**Comment by jviau** [comment] 2022-10-18 18:52
The "Always On" may not be applicable to v4. As this is not app services managing the lifetime of your worker, but the functions host. The host will be scaling worker in/out as necessary. Scaling in may terminate whatever worker which has this receiver in the background.  @fabiocav / @kshyju / @brettsam to correct me if I am wrong.

**Comment by kshyju** [comment] 2022-10-19 18:37
@gautamsamal Would you be able to share a minimal repro so that we can take a close look? A GitHub repo will be great. Thanks!

**Closed** 2022-10-26 19:01 UTC
Labels: Needs: Author Feedback, no recent activity
