### ISSUE TITLE
HttpRequestData.Cookies does not contain request cookies

### ISSUE THREAD

**Issue by UnoSD** [Azure/azure-functions-dotnet-worker#466] opened 2021-05-29 16:10 UTC
I have migrated a .NET Core 3.1 Function to .NET 5 and updated the code accordingly.

I used to be able to access cookies from `HttpRequest.Cookies` and I updated it to `HttpRequestData.Cookies`, but the collection seems to be empty on every request.

I was able to find the expected cookies using `HttpRequestData.Headers` and extracting them from there.

Req: `Cookie: jwtToken=VALUE`

Code:
```fsharp
[<Function("myfunc")>]
let run ([<HttpTrigger(AuthorizationLevel.Function, "get")>]req: HttpRequestData) =
    req.Cookies // This is an empty collection
```

`.NET 5.0.300`

```
Core Tools Version:       3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)
Function Runtime Version: 3.0.15828.0
```

Thank you

**Comment by fabiocav** [comment] 2021-06-02 23:02
Thanks for reporting. We'll take a look at this.

**Comment by kashimiz** [comment] 2021-06-17 22:00
I've been able to reproduce this in the following environment:

.NET 5.0.301

`Core Tools Version:       3.0.3477 Commit hash: 5fbb9a76fc00e4168f2cc90d6ff0afe5373afc6d  (64-bit)`
`Function Runtime Version: 3.0.15584.0`

Investigating root cause.

**Comment by kashimiz** [comment] 2021-06-22 19:34
The `RpcHttp` object used to construct `GrpcHttpRequestData` (implementation of `HttpRequestData`) has an empty collection for its `Cookies` property, which `GrpcHttpRequestData.Cookies` gets its value from:

https://github.com/Azure/azure-functions-dotnet-worker/blob/72b9d17a485eda1e6e3626a9472948be1152ab7d/src/DotNetWorker.Grpc/Http/GrpcHttpRequestData.cs#L69

Headers (including `Cookie`) come in on `RpcHttp.NullableHeaders`.

**Comment by fabiocav** [comment] 2021-06-24 20:15
Moving this to sprint 105 as we may need to understand if there's a problem in the host not populating the cookies collection int he HTTP representation.

**Comment by fabiocav** [comment] 2021-07-14 20:33
Moving this to 107 as it is a more realistic target given the current capacity

**Comment by satvu** [comment] 2021-09-10 17:31
The Cookies field is never populated in the host:

https://github.com/Azure/azure-functions-host/blob/4764c25d885cdfb1d84af3b80861b181ce658faa/src/WebJobs.Script.Grpc/MessageExtensions/GrpcMessageConversionExtensions.cs#L115`

Cookies are only passed through the headers, presumably to avoid duplicate data in the payload. We will be handling this bug on the worker side so it will only be a worker update not a host update.

**Comment by fabiocav** [comment] 2021-09-15 20:23
The root cause is now clear. Moving this to 110 for implementation.

**Closed** 2021-10-01 21:10 UTC
Labels: bug, needs-investigation
