### ISSUE TITLE
Exceptions are not cought by custom TelemetryProcesor in AppInsights

### ISSUE THREAD

**Issue by FilonenkoDmitry** [Azure/azure-functions-dotnet-worker#615] opened 2021-09-07 13:19 UTC
I'm trying to configure AppInsights for my Azure Function based on DotNet Worker. What I want to achieve is
1) to add some custom dimensions to logs
2) to not log exceptions in certain cases

In order to do this I configure AI with custom _TelemetryInitializer_ and  _TelemetryProcessor_. This works fine for traces and dependencies (i.e. custom dimensions are enriched with my custom key-value pairs). But it doesn't work for exceptions: they never end up in my TelemetryProcessor nor are their logs in AI complemeted with my custom dimensions.

Here is a list of NuGet packages used in my project:
```
"Microsoft.ApplicationInsights.WorkerService" Version="2.18.0"
"Microsoft.Azure.Functions.Worker" Version="1.5.1"
 "Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1"
 "Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4"
 "Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0"
 "Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4"
```
The code of custom initializer:
```
public class FunctionTelemetryInitializer : ITelemetryInitializer
    {
        public FunctionTelemetryInitializer(Config config)
        {
            _location = config.Location;
            _applicationName = config.ApplicationName;
            _version = config.Version;
        }

        private IEnumerable<KeyValuePair<string, string>> Values()
        {
            return new Dictionary<string, string>
            {
                {"location", _location},
                {"applicationName", _applicationName},
                {"applicationVersion", _version}
            };
        }
        
        public void Initialize(ITelemetry telemetry)
        {
            var props = telemetry.Context.GlobalProperties;
            foreach (var kvp in Values())
            {
                if (!props.ContainsKey(kvp.Key))
                {
                    props[kvp.Key] = kvp.Value;
                }
            }
        }
    }
```

The code of custom processor:
```
public class FunctionsTelemetryProcessor : ITelemetryProcessor
    {
        private ITelemetryProcessor _next;

        public FunctionsTelemetryProcessor(ITelemetryProcessor next)
        {
            _next = next;
        }
        
        public void Process(ITelemetry item)
        {
            if (item is TraceTelemetry trace)
            {
                if (trace.Message.Contains("Hello"))
                    return;        //here I have breakpoint 1
            }
            
            if (item is ExceptionTelemetry exception)
            {
  //here I have breakpoint 2
                var retryException =
                    exception.ExceptionDetailsInfoList.FirstOrDefault(s =>
                        s.TypeName.Contains(nameof(FunctionsRetryException)));
                if (retryException != null)
                {
                    return;
                }
            }
            _next.Process(item);
        }
    }
```
Function code:
```
[Function("Test")]
        public async Task Run([QueueTrigger("test", Connection = "Connection")]
            string message, FunctionContext context)
        {
            //when this line of code is uncommented, the breakpoint 1 in the processor is successfully hit
            //_logger.LogError("Hello!");

            //when the line above is commented out, the breakpoint 2 in the processor should be hit, but it's not
            throw new FunctionsRetryException("Test!!!");
        }
```

Program code:
```
public class Program
    {
        public static Task Main(string[] args)
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureServices(services =>
                {
                    var config = new ConfigurationBuilder()
                        .AddJsonFile("local.settings.json", true, true)
                        .AddEnvironmentVariables()
                        .Build()
                        .Get<FunctionsConfig>();
                    
                    services.AddSingleton<ITelemetryInitializer, FunctionTelemetryInitializer>();
                    services.AddApplicationInsightsTelemetryWorkerService();
                    services.AddApplicationInsightsTelemetryProcessor<FunctionsTelemetryProcessor>();

                    services.AddSingleton<Config>(config);
                })
                .Build();

            return host.RunAsync();
        }
    }
```
host.json:
```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "logging": {
    "fileLoggingMode": "never",
    "logLevel": {
      "default": "Information",
      "Host.Results": "Warning",
      "Function": "Warning",
      "Host.Aggregator": "Warning"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "maxTelemetryItemsPerSecond" : 20,
        "excludedTypes": "Request;Dependency;Exception"
      }
    }
  },
  "extensions": {
    "queues": {
      "maxPollingInterval": "00:00:02",
      "visibilityTimeout" : "00:05:00",
      "batchSize": 1,
      "maxDequeueCount": 3,
      "newBatchThreshold": 0
    }
  }
}
```

**Comment by FilonenkoDmitry** [comment] 2021-09-22 06:19
Hello! Any chance that anyone has seen it? Any feedback?

**Comment by pokrz26** [comment] 2021-12-03 12:56
It looks like RequestTelemetry also never end up in TelemetryProcessor.

**Comment by jviau** [comment] 2023-09-06 20:10
This is expected behavior. Those exceptions and telemetry items in question are from the _host_ process - the other end of a gRPC call. All customer code for dotnet isolated runs solely in the _worker_ process, AppInsights telemetry extensions will not apply to host process.

We do have an app insights package for the worker available now: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights. This will introduce just a new telemetry item worker side, but it won't address the existing concern - that is unavoidable and cannot be addressed.

Closing as by design.

**Closed by jviau** 2023-09-06 20:10 UTC
