### ISSUE TITLE
Azure functions can't be integration tested in dotnet 5

### ISSUE THREAD

**Issue by ffMathy** [Azure/azure-functions-dotnet-worker#472] opened 2021-06-03 00:08 UTC
Reference: https://github.com/Azure/azure-functions-dotnet-worker/issues/464

Not sure if functions were ever integration testable. However, I expect to be able to spawn up the function host in process, to enable debugging of tests, and run my functions like I normally would, but in an integration test. 

Today it's possible if I externally launch the functions core tools, but that doesn't record code coverage properly, and doesn't allow for placing breakpoints in the function call itself.

**Comment by fabiocav** [comment] 2021-06-10 21:13
This is a duplicate of #281 , which is currently in progress.

In the meantime, launching and testing OOP (the approach you've described) is the recommended approach.

Please follow the linked issue for updates. Thanks!

**Closed by fabiocav** 2021-06-10 21:13 UTC
Labels: Needs: Triage (Functions)
