### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by csharmi** [Azure/azure-functions-dotnet-worker#1912] opened 2023-09-18 15:17 UTC
Hello,
I would like to create a logger via middleware in an isolated-function with asp.net core integration.
I need to log the RequestBody and ResponseBody.
The extension UseHttpLogging() is not available.
Could someone point me how to start ?

Thanks

**Comment by kshyju** [comment] 2023-09-27 03:49
In aspnet, the `UseHttpLogging` extension method registers the `HttpLoggingMiddleware` to the request processing pipeline. As of today, we do not have any similar built-in middleware exist in functions.

But, you should be able to build this yourself in functions. Create a function [middleware](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#middleware), and inside the middleware you can get the `HttpContext` using the `GetHttpContext` extension method on `FunctionContext` instance. From that you can do whatever logging you want to do.

Check our [sample project](https://github.com/Azure/azure-functions-dotnet-worker/tree/sdk-1.14.1/samples/AspNetIntegration) in the repo. [Here is the line ](https://github.com/Azure/azure-functions-dotnet-worker/blob/7099e74643dd9412041f9332d20cea4ad6eb5907/samples/AspNetIntegration/RoutingMiddleware.cs#L16)to get HttpContext inside your function middleware.

**Comment by csharmi** [comment] 2023-09-28 13:04
Hello @kshyju,

Thanks for your feedback.
I already have a middleware doing what I want for asp.net, but I didn't find a way to re-use it in a function context application.
The tricky part was that the asp.net middleware does not implement IFunctionsWorkerMiddleware and the signature of the Invoke method is not the same.
IFunctionsWorkerMiddleware.Invoke( FunctionContext functionContext, FunctionExecutionDelegate next )
asp.net middleware: InvokeAsync( HttpContext context )

But finally, I managed to do it after lots of trial and errors by implementing this code in a IFunctionsWorkerMiddleware
```
public async Task Invoke( FunctionContext functionContext, FunctionExecutionDelegate next )
{
    var httpContext = functionContext.GetHttpContext();
    var loggingMiddleware = new LoggingMiddleware( new RequestDelegate( async ( httpContext ) =>
    {
        await next.Invoke( functionContext );

        //these lines are needed to catch the response body, needs to be used with custom Ok and BadRequestResult
        if ( functionContext.GetInvocationResult()?.Value is IActionResult actionResult )
        {
            ActionContext actionContext = new ActionContext( httpContext, httpContext.GetRouteData(), new ActionDescriptor() );
            await actionResult.ExecuteResultAsync( actionContext );
        }
    } ), this.loggingMiddlewareOptions, this._logger );

    await loggingMiddleware.InvokeAsync( httpContext );
}
```
Thanks

**Comment by kshyju** [comment] 2023-09-28 15:26
> the asp.net middleware does not implement IFunctionsWorkerMiddleware and the signature of the Invoke method is not the same.

Correct. This is by design. Keep in mind that azure functions are not just supporting http triggers, they support a wide variety of event triggers. The functions middleware implementation was created to handle those use cases.

But the extension method shared above give you access to HttpContext and you are free to do whatever you want to do with it. Looks like you got your stuff working. 

Closing as answered. Thanks!

**Closed by kshyju** 2023-09-28 15:26 UTC
Labels: Needs: Attention :wave:, logging, feature: HTTP types
