### ISSUE TITLE
Spurious build failures on `extensions.json`

### ISSUE THREAD

**Issue by Porges** [Azure/azure-functions-dotnet-worker#2614] opened 2024-07-17 23:32 UTC
### Description

We recently updated the Worker SDK and .NET versions on our build and are now seeing the following error occasionally. It does not happen on every build:

```
dotnet/sdk/8.0.303/Microsoft.Common.CurrentVersion.targets(5270,5):
error MSB3030: Could not copy the file ".../Debug/net8.0/extensions.json" because it was not found.
```

### Steps to reproduce

The versions we are now using are .NET 8.0.303 and Microsoft.Azure.Functions.Worker.Sdk 1.17.4. The previous SDK version was 1.17.2.

**Comment by satvu** [comment] 2024-07-18 17:35
Likely related to #2601 - are you using any custom build steps?

**Comment by Porges** [comment] 2024-07-18 20:21
> @satvu Likely related to #2601 - are you using any custom build steps?

Not that I'm aware of. I'll try to get a binary build log that repros the failure.

**Comment by ef-darrenalford** [comment] 2024-07-24 14:30
we're also seeing this issue. one project seemed to fail every other build, and a second failed every time.

same versions as reported - downgrading sdk to 1.17.2 "fixed" the issue.

**Comment by jviau** [comment] 2024-07-31 15:40
Duplicate of #2601

**Closed by jviau** 2024-07-31 15:40 UTC
Labels: Needs: Attention :wave:, area: sdk, potential-bug
