### ISSUE TITLE
Microsoft.Azure.Functions.Worker.Sdk 1.16.2 -> 1.16.3 issues

### ISSUE THREAD

**Issue by jdholbrook81** [Azure/azure-functions-dotnet-worker#2132] opened 2023-12-06 15:35 UTC
I am updating dependencies, encountered a build failure when I updated Microsoft.Azure.Functions.Worker.Sdk 1.16.2 to 1.16.3. 

I get several errors in a generated file that I can't modify.

WorkerExtensionStartupCodeExecutor.g.cs
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/7423387/e761b6ba-1ccf-49d5-850d-8bb96b42925b)

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/7423387/6bfd5bab-e6d8-4a40-ace3-169c811df70e)

**Comment by kshyju** [comment] 2023-12-06 16:15
Closing as dupe of #2114 . See https://github.com/Azure/azure-functions-dotnet-worker/issues/2114#issuecomment-1840088691

**Closed by kshyju** 2023-12-06 16:15 UTC
Labels: Needs: Triage (Functions)
