### ISSUE TITLE
dotnet build in Azure Pipeline still requires NET Core 3.1

### ISSUE THREAD

**Issue by RyanMarcotte** [Azure/azure-functions-dotnet-worker#332] opened 2021-03-20 03:40 UTC
The error message looks similar to #297 .  The pipeline fails at the `dotnet build` step.

```
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2 
  displayName: ".NET Core 5.0.x"
  inputs:
    version: '5.0.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: 'src/BrewNinja.Integration.SquareCatalog.Functions.sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'src/BrewNinja.Integration.SquareCatalog.Functions.sln'
    arguments: '--configuration $(BuildConfiguration) --no-restore'
    versioningScheme: byBuildNumber
```

I have added `<_FunctionsExtensionTargetFramework>netstandard2.0</_FunctionsExtensionTargetFramework>` to the functions project as documented [here](https://github.com/Azure/azure-functions-dotnet-worker/wiki/Known-issues#net-core-31-dependency).

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
	<LangVersion>preview</LangVersion>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
	<OutputType>Exe</OutputType>
	<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
	<_FunctionsExtensionTargetFramework>netstandard2.0</_FunctionsExtensionTargetFramework> <!-- https://github.com/Azure/azure-functions-dotnet-worker/wiki/Known-issues#net-core-31-dependency -->
	<Nullable>enable</Nullable>
  </PropertyGroup>
  <!-- also tried removing this, but didn't affect anything -->
  <Target Name="CopyRuntimes" AfterTargets="AfterBuild" Condition=" '$(OS)' == 'UNIX' ">
    <!-- To workaround a bug where the files aren't copied correctly for non-Windows platforms -->
    <Exec Command="rm -rf $(OutDir)bin/runtimes/* &amp;&amp; mkdir -p $(OutDir)bin/runtimes &amp;&amp; cp -R $(OutDir)runtimes/* $(OutDir)bin/runtimes/" />
  </Target>
  <ItemGroup>
    <PackageReference Include="Functional.Primitives.SerilogExtensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.12" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.1" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="4.0.0" />
    <PackageReference Include="Serilog.Exceptions" Version="6.1.0" />
    <PackageReference Include="SimpleInjector" Version="5.3.0" />
    <PackageReference Include="SimpleInjector.Integration.GenericHost" Version="5.3.0" />
    <PackageReference Include="SimpleInjector.Integration.ServiceCollection" Version="5.3.0" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BrewNinja.Infrastructure.Common\BrewNinja.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\BrewNinja.Integration.SquareCatalog.Module\BrewNinja.Integration.SquareCatalog.Module.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

```
2021-03-20T03:19:59.4980413Z ##[section]Starting: dotnet build
2021-03-20T03:19:59.4992063Z ==============================================================================
2021-03-20T03:19:59.4992326Z Task         : .NET Core
2021-03-20T03:19:59.4992617Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
2021-03-20T03:19:59.4992894Z Version      : 2.181.0
2021-03-20T03:19:59.4993082Z Author       : Microsoft Corporation
2021-03-20T03:19:59.4993388Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
2021-03-20T03:19:59.4993707Z ==============================================================================
2021-03-20T03:19:59.8056434Z Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
2021-03-20T03:19:59.8102667Z [command]/opt/hostedtoolcache/dotnet/dotnet build /home/vsts/work/1/s/src/BrewNinja.Integration.SquareCatalog.Functions.sln -dl:CentralLogger,"/home/vsts/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.181.0/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"*ForwardingLogger,"/home/vsts/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.181.0/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" --configuration Release --no-restore
2021-03-20T03:20:00.0375020Z Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
2021-03-20T03:20:00.0376592Z Copyright (C) Microsoft Corporation. All rights reserved.
2021-03-20T03:20:00.0377301Z 
2021-03-20T03:20:02.4106199Z   BrewNinja.Infrastructure.Common -> /home/vsts/work/1/s/src/BrewNinja.Infrastructure.Common/bin/Release/net5.0/BrewNinja.Infrastructure.Common.dll
2021-03-20T03:20:02.7538343Z   BrewNinja.Integration.SquareCatalog.Module -> /home/vsts/work/1/s/src/BrewNinja.Integration.SquareCatalog.Module/bin/Release/net5.0/BrewNinja.Integration.SquareCatalog.Module.dll
2021-03-20T03:20:02.8712223Z   BrewNinja.Integration.SquareCatalog.TestInfrastructure -> /home/vsts/work/1/s/src/BrewNinja.Integration.SquareCatalog.TestInfrastructure/bin/Release/net5.0/BrewNinja.Integration.SquareCatalog.TestInfrastructure.dll
2021-03-20T03:20:03.9099033Z   BrewNinja.Integration.SquareCatalog.Functions -> /home/vsts/work/1/s/src/BrewNinja.Integration.SquareCatalog.Functions/bin/Release/net5.0/BrewNinja.Integration.SquareCatalog.Functions.dll
2021-03-20T03:20:04.4494379Z   Determining projects to restore...
2021-03-20T03:20:06.7551774Z   BrewNinja.Integration.SquareCatalog.Functions.Tests -> /home/vsts/work/1/s/src/BrewNinja.Integration.SquareCatalog.Functions.Tests/bin/Release/net5.0/BrewNinja.Integration.SquareCatalog.Functions.Tests.dll
2021-03-20T03:20:06.9999977Z   BrewNinja.Integration.SquareCatalog.Module.Tests -> /home/vsts/work/1/s/src/BrewNinja.Integration.SquareCatalog.Module.Tests/bin/Release/net5.0/BrewNinja.Integration.SquareCatalog.Module.Tests.dll
2021-03-20T03:20:09.6410041Z   Restored /tmp/afsoddch.2dp/WorkerExtensions.csproj (in 2.73 sec).
2021-03-20T03:20:09.6965979Z ##[warning]/home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.targets(74,5): Warning : The ExtensionsMetadataGenerator package was not imported correctly. Are you missing '/home/vsts/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.2.0/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets' or '/home/vsts/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.2.0/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.props'?
2021-03-20T03:20:09.6978164Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.targets(74,5): warning : The ExtensionsMetadataGenerator package was not imported correctly. Are you missing '/home/vsts/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.2.0/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets' or '/home/vsts/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.2.0/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.props'? [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.7872689Z   WorkerExtensions -> /tmp/afsoddch.2dp/buildout/Microsoft.Azure.Functions.Worker.Extensions.dll
2021-03-20T03:20:09.8024685Z ##[error]/home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): Error : It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.4 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64

2021-03-20T03:20:09.8028967Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8031110Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8033478Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - The following frameworks were found: [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8035448Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :       5.0.4 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App] [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8036424Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8037361Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : You can resolve the problem by installing the specified framework and/or SDK. [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8038234Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8039477Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The specified framework can be found at: [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8041504Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64 [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8042521Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8045185Z ##[error]/home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): Error : Metadata generation failed.
2021-03-20T03:20:09.8046503Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : Metadata generation failed. [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8099340Z 
2021-03-20T03:20:09.8101823Z Build FAILED.
2021-03-20T03:20:09.8102155Z 
2021-03-20T03:20:09.8104379Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.targets(74,5): warning : The ExtensionsMetadataGenerator package was not imported correctly. Are you missing '/home/vsts/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.2.0/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets' or '/home/vsts/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.2.0/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.props'? [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8105976Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8107426Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8108796Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - The following frameworks were found: [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8109799Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :       5.0.4 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App] [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8110734Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8111656Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : You can resolve the problem by installing the specified framework and/or SDK. [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8112671Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8113506Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The specified framework can be found at: [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8114916Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64 [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8115974Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8116775Z /home/vsts/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : Metadata generation failed. [/tmp/afsoddch.2dp/WorkerExtensions.csproj]
2021-03-20T03:20:09.8117296Z     1 Warning(s)
2021-03-20T03:20:09.8117518Z     2 Error(s)
2021-03-20T03:20:09.8117644Z 
2021-03-20T03:20:09.8117870Z Time Elapsed 00:00:09.72
2021-03-20T03:20:09.8334548Z ##[error]Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 1
2021-03-20T03:20:09.8337398Z ##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
2021-03-20T03:20:09.8341130Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
2021-03-20T03:20:09.8343810Z ##[error]Dotnet command failed with non-zero exit code on the following projects : /home/vsts/work/1/s/src/BrewNinja.Integration.SquareCatalog.Functions.sln
2021-03-20T03:20:09.8386082Z ##[section]Finishing: dotnet build
```

**Comment by fabiocav** [comment] 2021-03-20 05:34
This is indeed the same issue. At the moment, 3.1 in the build environment is a requirement.

We'll continue updating the other issue, so I'll close this one as a duplicate. Thanks for reporting!

Duplicate of #297

**Closed by fabiocav** 2021-03-20 05:34 UTC
Labels: Needs: Triage (Functions)
