### ISSUE TITLE
ServiceBusTrigger ignores some configuration providers

### ISSUE THREAD

**Issue by zvrba** [Azure/azure-functions-dotnet-worker#2727] opened 2024-09-23 07:11 UTC
### Description

On NET8 using the latest version (5.22.0) of Microsoft.Azure.Worker.Extensions.ServiceBus. My function signature looks like this

```
        public async Task Run(
            [ServiceBusTrigger("myqueue", Connection = "ServiceBus")]
            ServiceBusReceivedMessage message,
            ServiceBusMessageActions messageActions)
```

`ServiceBus` key is defined in Azure App Configuration service; the definition looks like this when inspecting configuration on the host object:
```
{Path = ServiceBus}
{Path = ServiceBus:FullyQualifiedNamespace, Value = <redacted>.servicebus.windows.net, Provider = AzureAppConfigurationProvider}
```
Running the function results in the following error in console output: "The listener for function 'Functions.DrainV1' was unable to start. Microsoft.Azure.WebJobs.Extensions.ServiceBus: Service Bus account connection string with name 'ServiceBus' does not exist in the settings. Make sure that it is a defined App Setting.".

On the other hand, when I use `Connection = "ServiceBusX"` with the following definition in the configuration
```
{Path = ServiceBusX}
{Path = ServiceBusX:FullyQualifiedNamespace, Value = <redacted>.servicebus.windows.net, Provider = EnvironmentVariablesConfigurationProvider}
```
the function starts up successfully.

Note that the *only* difference in the definitions of `ServiceBus` and `ServiceBusX` is the configuration provider.

### Steps to reproduce

Set up a simple functions project with app configuration provider as follows (the settings are for local development) and single function with service bus trigger as given in the description.
```
    private static void Main(string[] args)
    {
        var opts = new Azure.Identity.DefaultAzureCredentialOptions
        {
            ExcludeManagedIdentityCredential = true,
            ExcludeWorkloadIdentityCredential = true,
        };
        var host = new HostBuilder()
            .ConfigureAppConfiguration(b =>
            {
                b.AddAzureAppConfiguration(o => o.Connect(
                    new Uri("https://<redacted>.azconfig.io"),
                    new Azure.Identity.DefaultAzureCredential(opts)));
            })
            .ConfigureFunctionsWebApplication()
            .ConfigureServices(services =>
            {
                services.AddApplicationInsightsTelemetryWorkerService();
                services.ConfigureFunctionsApplicationInsights();
                services.AddSingleton<IAuditRecordWriter, AuditRecordWriterV1>();
            })
            .Build();
```

Define `ServiceBus` connection in azure app configuration, and `ServiceBusX` connection in `local.settings.json`. Try using both in `ServiceBusTrigger`; when using `ServiceBus` the function fails to start up; when using `ServiceBusX` the function starts up successfully.

**Comment by pctrung** [comment] 2024-10-02 11:01
I am experiencing the exact same issue as you, where the Connection attribute parameter of ServiceBusTrigger cannot be retrieved from **`Azure App Configuration`**, but it works fine when retrieved from **`local.settings.json`**. 
Additionally, there is also an issue with using `%queueNameInConfiguration% `to get the queue name from **Azure App Configuration** (but it also works fine with `local.settings.json`). 

Moreover, I am facing a similar issue with `TimerTrigger`. I believe this issue occurs with attributes that use configuration values from a provider other than local, such as Azure App Configuration.

The steps to reproduce are the same as yours. Thank you, Azure team, for looking into this issue. I look forward to your response.

**Comment by nicoletahermeneanu** [comment] 2024-11-07 13:33
I am facing the same issue as @pctrung with queue name and Connection attribute. 

Is there any solution for it?

**Comment by paulinventome** [comment] 2024-11-21 11:44
To add another voice, I am seeing the same issues across not Just ServiceBusTrigger but BlobTrigger and I imagine the rest of them.

They don't seem to be looking in App Configuration as a provider for anything at the moment.

Also going beyond that I've found that combining App Configuration and Managed Identity gets even less support because I don't think it's able to look at the whole __ syntax, even when we change that to a :

For example variablename_fullyQualifiedNamespace works in local settings but the same in App Configuration just doesn't resolve and I've tried every way I can think of.

**Comment by almightydegu** [comment] 2024-12-03 15:23
whats interesting with this is that it appears to not look at any of the configuration providers.

I tried to add the connection string to the environment variables:

```csharp
var serviceBusConnection = builder.Configuration["ServiceBus:Namespace"];

Environment.SetEnvironmentVariable("ServiceBusConnection:fullyQualifiedNamespace", serviceBusConnection);

builder.Configuration.AddEnvironmentVariables();
```

So it looks like this:

```
{Path = ServiceBusConnection:fullyQualifiedNamespace, Value = <<REDACTED>>, Provider = EnvironmentVariablesConfigurationProvider}
```

But I still get "Make sure that it is a defined App Setting"

As a bonus, I tried manually setting it after loading the `local.settings.json` 

```csharp
builder.Configuration
    .SetBasePath(Environment.CurrentDirectory)
    .AddJsonFile("host.json", true)
    .AddJsonFile("local.settings.json", true);

builder.Configuration["ServiceBusConnection:fullyQualifiedNamespace"] = "<<REDACTED>>";
```

and that looks like this

```
{Path = ServiceBusConnection:fullyQualifiedNamespace, Value = <<REDACTED>>, Provider = JsonConfigurationProvider for 'local.settings.json' (Optional)}
```

But even with the provider being `'local.settings.json` still didn't work.

**Comment by jviau** [comment] 2024-12-04 21:41
@zvrba trigger-influencing configuration cannot come from a source that only the worker knows about, this includes Azure AppConfiguration. The problem is that there are platform components which need to have the fully resolved trigger **without** ever starting your application (otherwise scale to 0 would never work!)

All parameterization and connections used in triggers must come from [function app settings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=azure-portal%2Cto-premium). This method allows for the platform components to resolve your service bus and support scaling and triggering.

**Comment by zvrba** [comment] 2024-12-05 13:16
Ok, that's a bummer because I was hoping to be able to use AppConfiguration to have a _central_ tidy place for managing all of configuration settings for a set of interconnected components. That function triggers don't work with AppConfiguration kind of defeats the point of AppConfiguration because some settings still have to be set/updated at multiple places. (Instead of having _one_ "App setting" with AppConfiguration URI.)

Well then. Should I put trigger configuration under "App settings" or "Connection strings", and what's the difference anyway?

**Comment by jviau** [comment] 2024-12-05 17:34
@zvrba use "App Settings" and not "Connection strings". The latter is intended for older language stacks such as Asp.Net (the pre-.netcore one).

For organizing secrets, app settings does support keyvault references (but not Azure AppConfiguration): https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli

**Comment by zvrba** [comment] 2024-12-06 07:06
@jviau Thanks for the tips.

A side-note: Previously we did use KeyVault for storing config settings, but switched to Azure AppConfiguration because it has nicer UI and import/export capabilities. KeyVault secrets are _very_ clunky to use as config store: in Azure portal, just try to count the number of clicks needed to show or edit a particular setting in KeyVault vs AppConfiguration.

Maybe we just make a simple console app that presents the contents of KV in an easy to read and edit form and revert to using KV.

Out of curiosity: what was the point of releasing AppConfiguration instead of building a nicer UI for KV?

**Comment by jviau** [comment] 2024-12-09 17:10
> Out of curiosity: what was the point of releasing AppConfiguration instead of building a nicer UI for KV?

Those are both separate products from Azure Functions, so our team would not have any context on that.

Going to close this as the question is answered.

**Closed by jviau** 2024-12-09 17:10 UTC
Labels: question, Needs: Attention :wave:, area: configuration

**Comment by VenkatSappidi** [comment] 2025-02-13 22:35
@pctrung Did you able to figure out solution. I am having the same problem, both binding and Connection string is having issues

**Comment by pctrung** [comment] 2025-02-16 12:04
I found solution for it and here is my investigation for your reference:

Azure Functions in .NET 8 isolated mode do not support custom configuration sources like Azure App Configuration for triggers and bindings. [Microsoft Documentation](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=hostbuilder%2Cwindows#:~:text=Custom%20configuration%20sources,Configuration%20references%20features)

To work around this limitation, I used the following approaches:

**1. Environment Variables:**
Store configuration values in Azure Function App environment variables.
Use normal values, Key Vault references, or App Configuration references instead of directly linking to App Configuration via a connection string.

**2. Custom IFunctionMetadataProvider Implementation:**
Implement a custom class that implements IFunctionMetadataProvider to generate metadata for placeholders like %token%.
[Detailed Implementation](https://stackoverflow.com/questions/78897966/azure-functions-trigger-variables-isolated-functions)

**🚨 Note:** This approach does not work for connection strings. It only applies to placeholders like %TopicName%, %SubscriptionName%, etc.

**Current Solution:**
I use both approaches:
Approach 1 for storing ConnectionString.
Approach 2 for other placeholders.

Hope this helps!

**Comment by alasdaircs** [comment] 2025-08-04 23:02
I've taken other's work, particularly the code from [Amelsfort](https://github.com/Amelsfort) in https://github.com/Azure/azure-webjobs-sdk/issues/3070#issuecomment-2455260085 to create this slightly more complete [gist](https://gist.github.com/alasdaircs/78f941c6ce007a9f3ac6ce430abedaca) - that works for now.

In your program.cs:

```
using AcsSolutions.Extensions.Azure.Functions;

builder.Services.AddConfigurationBoundFunctionMetadataProvider();
```

**Comment by phatcher** [comment] 2025-08-12 22:52
@alasdaircs There's one more trick I applied to your code which was to inject a parameters object which allows you to specify a section name for the tokens so they can all be clustered together.
