### ISSUE TITLE
Issue 556 closed without resolution

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#815] opened 2022-03-03 02:31 UTC
Seems like #556 was closed without resolution then locked to prevent further discussion

> This is a very generic error and the issue has collected incidents with a number of different root causes.

> The initial problem has been addressed. Anyone else experiencing this problem, can you please open a new issue with the details (beyond the top level error) so we can take a closer look?

If the same error has many root causes... that means there's an issue with error reporting. More specific errors need to be surfaced so that they're easier to track down. If "Did not find any initialized language workers" is the error for a whole host of issues **in and of itself is an issue**

**Comment by fabiocav** [comment] 2022-03-15 21:23
@onionhammer Yes, you're correct and that is being addressed in the host. The runtime will be surfacing more detailed information that will enable end users (and the team) to better understand the root cause. In the meantime, having distinct issues for those scenarios helps us better assist people running into problems as we can focus exactly on what is impacting them and rely on the app information provided when the issue is opened to take a closer look at traces.

We're actively working on that and should see that error moving away in favor of more detailed information.

Hope this helps!

**Closed** 2022-03-23 01:00 UTC
Labels: Needs: Author Feedback, no recent activity
