### ISSUE TITLE
Clarification on "Disabled" Functions

### ISSUE THREAD

**Issue by redtaped** [Azure/azure-functions-dotnet-worker#438] opened 2021-05-05 15:07 UTC
How can we disable a function in a staging slot to prevent it from picking up work from triggers?

- Does the [old documentation](https://docs.microsoft.com/en-us/azure/azure-functions/disable-function?tabs=portal) still apply?
- Does AzureWebJobs.<FUNCTION_NAME>.Disabled still work even though it says "WebJobs"?
- Is [Disabled] attribute in C# still supported? 
- Is there a way to disable ALL functions on staging slot?

What I'm trying to accomplish is to make sure we can swap slots, but then afterwards, the staging slot won't pick up any work from servicebus queues, and timer jobs will no longer run.

**Comment by brettsam** [comment] 2021-05-07 14:47
Thanks for the questions! Hope these answers help.

>Does the old documentation still apply?

Yes, other than the `[Disabled]` attribute, as that does not apply to isolated.

> Does AzureWebJobs.<FUNCTION_NAME>.Disabled still work even though it says "WebJobs"?

Yes, this continues to work and is the recommended way to handle disabling for slots.

>Is [Disabled] attribute in C# still supported?

This is not currently supported for isolated C# apps. Related: https://github.com/Azure/azure-functions-dotnet-worker/issues/312

>Is there a way to disable ALL functions on staging slot?

There is not.

I'm going to close this as a dupe of #312.

**Closed by brettsam** 2021-05-07 14:47 UTC
Labels: Needs: Triage (Functions)
