### ISSUE TITLE
Logging shows no output from functions

### ISSUE THREAD

**Issue by MO2k4** [Azure/azure-functions-dotnet-worker#1140] opened 2022-10-25 08:11 UTC
Hey

i am using Microsoft.Azure.Functions.Worker.ApplicationInsights 1.0.0-pre3 and i can't see any output from my own logging inside the functions.

Currently my code looks like this:

```cs
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder => builder.AddApplicationInsights().AddApplicationInsightsLogger())
    .ConfigureLogging(builder => 
    {
            builder.AddConsole();
            builder.Services.Configure<LoggerFilterOptions>(options => options.Rules.Clear());
    });
```

The last line was needed to get the logging towards Application Insights working. There was an issue mentioned by @brettsam 

My function uses the ILogger<T> from the DI, but i can't see anything on the console - Application Insights shows every log entry.

**Comment by elsand** [comment] 2022-10-26 07:24
Duplicate of #1090 ?

**Comment by jviau** [comment] 2023-06-28 22:14
@MO2k4 I am unable to reproduce this. Adding the console logger via `.ConfigureLogging(builder => builder.AddConsole())` and logging from within a function outputs to console for me (using `.LogInformation`). I am also including the rule clearing call. Can you try again and see if you aren't adding filters later on in the startup?

Even without the `.AddConsole` I do see console logs show up. This is because we send logs over gRPC back to the host, which writes to the console for you. We will be removing this behavior eventually, and instead have the worker rely on `.AddConsole` only. Not sure when this will happen though.

**Closed** 2023-07-06 04:01 UTC
Labels: Needs: Author Feedback, no recent activity, logging, application-insights
