### ISSUE TITLE
Trace level log presented in log stream with Information log level Settings

### ISSUE THREAD

**Issue by RetYn** [Azure/azure-functions-dotnet-worker#1029] opened 2022-09-09 01:02 UTC
my host.json
function version v4
```   
 {
        "version": "2.0",
	"logLevel": {
		"logLevel": {
			"default": "Information"
		}
	},
	"logging": {
		"applicationInsights": {
			"samplingSettings": {
				"isEnabled": true,
				"excludedTypes": "Request"
			}
		}
	}
}
```
In application insights, log level is correct, no trace level log is recorded 
But In log stream and Azure Code+Test panel, I can see log level output [verbose] for httpclient that will cause HTTP header
authority leak.
I do not set any custom log handler in IHttpClientFactory. HttpClient created by IHttpClientFactory will log request header in trace level but it should not be
![image](https://user-images.githubusercontent.com/7384252/189251993-712071ee-b1ff-4ab0-a3d9-b6cbc679f13b.png)

but in application all is information
![image](https://user-images.githubusercontent.com/7384252/189268942-6872160e-f289-47b5-9e15-cd93df84af36.png)

I cannot determine whether my service is under safety conditions.

**Comment by RetYn** [comment] 2022-09-12 11:08
#796 Does my issue related to this? 
The difference between us is the log level recorded in application insights.

**Comment by RohitRanjanMS** [comment] 2022-09-16 03:52
Hi @RetYn this is by design. Filters are applied only for the data that is stored in ApplicationInsights. 
What you see in the log streaming is not stored anywhere. Data is streamed directly from the AI SDK to the UI (Azure portal). This is only for the duration for which you have the UI open and there's timeout as well. The purpose of log streaming is to get a quick pulse of the function execution. Additionally, it has performance impact on the function execution as the AI SDK is doing additional work of streaming. Log streaming is throttled and if the volume is too high, you will notice some missing telemetry as well.
You can configure HTTP Client not to generate these logs.

**Comment by RetYn** [comment] 2022-09-16 05:48
@RohitRanjanMS 
Thanks for you confirm.
But that's really strange behavior because I can not see those logged in the console when I run locally and when I deployed to the azure , I will see it.

**Comment by RohitRanjanMS** [comment] 2022-09-16 14:00
Hi @RetYn you can read about the Live Metrics (log streaming) [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream). Code + Test also uses live metrics, but it's filtered to reduce the noise. AI -> Live Metrics shows everything.

**Comment by kshyju** [comment] 2022-09-17 00:10
Closing as answered.

**Closed by kshyju** 2022-09-17 00:10 UTC
Labels: Needs: Triage (Functions)
