### ISSUE TITLE
Allow hyphen in function name

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-dotnet-worker#108] opened 2021-02-09 22:29 UTC
A function name with hyphen, for example, breaks build. https://github.com/Azure/azure-functions-dotnet-worker-preview/issues/34

**Comment by SeanFeldman** [comment] 2021-02-09 22:33
@anthonychu, any specific reason why not to move the issue from the original repository here? It will retain all the notifications but would reduce the brain split of finding to different issues in two repositories. Thanks.

**Comment by anthonychu** [comment] 2021-02-09 22:36
@SeanFeldman We're going to move everything over here soon.

**Comment by fabiocav** [comment] 2021-02-26 01:02
Duplicate of #182

**Closed by fabiocav** 2021-02-26 01:02 UTC
Labels: bug
