### ISSUE TITLE
How to add Azure Key Vault Secret value inside the Connection parameter of EventHub Output binding attribute?

### ISSUE THREAD

**Issue by ahsanhabib91** [Azure/azure-functions-dotnet-worker#867] opened 2022-04-27 19:18 UTC
I have a simple Azure Function **.NET 6 Isolated process** with **HttpTrigger** which sends data to **EventHub** through **output binding**. The Output binding attribute is like `[EventHubOutput("my-eh", Connection = "EventHubConnectionString")]`. Now, I would like to set the **EventHubConnectionString** from a **Secret** saved in **Azure Key Vault**. How to do it?

**Note:** I know [Key Vault references](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references) is a good solution. But this doesn't work **locally** and we don't want to save **secrets** inside **local.settings.json** either. 

Here is my **Program.cs:**
```
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;
using Microsoft.Extensions.Hosting;

var kvUri = $"https://{Environment.GetEnvironmentVariable("KEY_VAULT_NAME")}.vault.azure.net";
var secretClient = new SecretClient(new Uri(kvUri), new DefaultAzureCredential());
var secret = await secretClient.GetSecretAsync("EventHubConnectionString");
// would like to use this value as EventHubConnectionString inside the Connection parameter of EventHubOutput attribute
var eventHubConnectionString = secret.Value.Value; 

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .Build();

host.Run();
```
Here is my **Function.cs:**
```
using System.Net;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace FuncManagedIdentities;

public class ManagedIdentitiesFunction
{
    private readonly ILogger _logger;

    public ManagedIdentitiesFunction(ILoggerFactory loggerFactory)
    {
        _logger = loggerFactory.CreateLogger<ManagedIdentitiesFunction>();
    }

    [Function(nameof(ManagedIdentitiesFunction))]
    public async Task<OutputType> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
    {
        return new OutputType()
        {
            OutputEvent = $"{nameof(ManagedIdentitiesFunction)}: OutputEvent Message received at {DateTime.Now}",
            HttpResponse = req.CreateResponse(HttpStatusCode.OK)
        };
    }
}

public class OutputType
{
    [EventHubOutput("my-eh", Connection = "EventHubConnectionString")]// EventHubConnectionString should be set from KeyVault Secret
    public string OutputEvent { get; set; }

    public HttpResponseData HttpResponse { get; set; }
}
```

**Comment by fabiocav** [comment] 2022-05-04 18:32
Duplicate of #869

**Closed by fabiocav** 2022-05-04 18:32 UTC
Labels: Needs: Triage (Functions)
