### ISSUE TITLE
Handling WorkerTerminate message for graceful shutdown of dotnet worker

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-dotnet-worker#870] opened 2022-05-02 18:19 UTC
Host will send a [WorkerTerminate](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/58b3dc0dbde065b15bd979bd2e27f36b7ee6273e/src/proto/FunctionRpc.proto#L39) message to worker to allow the worker to terminate itself gracefully instead of immediately killing it. Worker to act on this signal and send Success response to Host.

Related issue on Host side - https://github.com/Azure/azure-functions-host/issues/2308

**Comment by kshyju** [comment] 2022-05-20 23:38
#192 might be a dupe of this.

**Closed** 2022-06-01 20:35 UTC
