### ISSUE TITLE
FromResult error when namespace ends in .Task

### ISSUE THREAD

**Issue by jruelnurses** [Azure/azure-functions-dotnet-worker#2611] opened 2024-07-17 19:28 UTC
### Description

Receive a "The type or namespace name 'FromResult' does not exist in the namespace 'project namespace' error when the project name/namespace ends with .Task

Error comes from GeneratedFunctionMetadataProvider.g.cs

Minimal Example
https://github.com/jruelnurses/TaskBug.Task

### Steps to reproduce

Create a new Azure Function project targeting .net8 with the project name ending with .Task, try to run the function.

**Comment by DL444** [comment] 2024-09-01 21:37
[Code](https://github.com/Azure/azure-functions-dotnet-worker/blob/4ef9d3c27740d3df5c060729777a8dc63d468e9a/sdk/Sdk.Generators/FunctionMetadataProviderGenerator/FunctionMetadataProviderGenerator.Emitter.cs#L52) produced by the function metadata code generator calls `Task.FromResult` intending for `System.Threading.Tasks.Task.FromResult`. This will introduce namespace ambiguation if the project namespace ends with `.Task` or references another project with a common prefix and ends with `.Task`.

```cs
public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
{
    // ...
    return Task.FromResult(metadataList.ToImmutableArray());
}
```

This should be fixed by using fully qualified namespace instead. I may contribute in a few days.

```diff
- return Task.FromResult(metadataList.ToImmutableArray());
+ return global::System.Threading.Tasks.Task.FromResult(metadataList.ToImmutableArray());
```

By the way this is the third time I've seem similar namespace ambiguity issues caused by code generation in this repo. I think I've seen this type of problems being reported against `System.Text.Json` code generator as well. Seems to me like a common pitfall that is worthy of some guidelines from the .NET team.

**Closed** 2024-10-16 18:06 UTC
Labels: Needs: Triage (Functions), potential-bug
