### ISSUE TITLE
Enable "SharedMemoryDataTransfer"

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-dotnet-worker#114] opened 2021-02-10 00:49 UTC
See: https://github.com/Azure/azure-functions-host/wiki/Out-of-Proc-Worker-Capabilities#sharedmemorydatatransfer
Improves perf

**Comment by fabiocav** [comment] 2021-02-12 04:29
Duplicate of #105

**Closed by fabiocav** 2021-02-12 04:29 UTC
