### ISSUE TITLE
NET 8 there is some issue with package `Microsoft.Azure.Functions.Worker.Sdk` version `1.17.0` and `1.17.1` when run with some other function dependencies. same code working fine with same code with version `1.16.4` .

### ISSUE THREAD

**Issue by Shandilyavivek** [Azure/azure-functions-dotnet-worker#2309] opened 2024-02-29 12:05 UTC
### Description

NET 8 there is some issue with package `Microsoft.Azure.Functions.Worker.Sdk` version `1.17.0` and `1.17.1` when run with some other function dependencies. Http trigger and timer trigger working fine. But Queue trigger is throwing error. same code for Queue trigger working fine with version `1.16.4` . 

Other packages are latest version. 

### Steps to reproduce

please check this SQ thread. https://stackoverflow.com/questions/78067439/net-8-function-app-doesnt-load-functions-from-dependencies/78074480?noredirect=1#comment137650419_78074480

v1.17.1 error: https://i.imgur.com/jKf9RJL.png
v1.17.0 sometimes works fine (https://i.imgur.com/R3IWL95.png) sometime throws error (https://i.imgur.com/DoNNG6n.png)
lower version are working fine. v1.16.4

**Comment by kshyju** [comment] 2024-02-29 17:20
Thanks for reporting. We will take a look and get back to you as soon as we can.

**Comment by satvu** [comment] 2024-03-01 22:29
Hi @Shandilyavivek can you upgrade to SDK version 1.17.2 and see if that resolves your issue?

**Comment by Shandilyavivek** [comment] 2024-03-04 03:26
@satvu Thanks, I used v1.17.2 and it fixed the issue.

**Comment by Shandilyavivek** [comment] 2024-03-04 05:09
Hi @satvu if possible, Could you please explain the reason why v1.17.0 and v1.17.1 was causing the issue?

**Comment by davidpeden3** [comment] 2024-03-04 05:28
> Hi @satvu if possible, Could you please explain the reason why v1.17.0 and v1.17.1 was causing the issue?

https://github.com/Azure/azure-functions-dotnet-worker/pull/1946 was the root cause of all of these recently reported issues so they rolled that commit back in `1.17.2`. see https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.17.2 for details.

**Comment by satvu** [comment] 2024-03-06 19:32
Closing as resolved.

**Closed by satvu** 2024-03-06 19:32 UTC
Labels: bug
