### ISSUE TITLE
Azure Function Isolated Mode - Application Insights Configuration

### ISSUE THREAD

**Issue by olandese** [Azure/azure-functions-dotnet-worker#1123] opened 2022-10-14 07:28 UTC
Reply to: https://github.com/Azure/azure-functions-dotnet-worker/issues/760#issuecomment-1264365463

Hi @brettsam,

thank you for your reply in the other thread.

The configuration for the host and the function is different/separate, clear. 

If I understand well, in the https://github.com/Azure/azure-functions-dotnet-worker/pull/944#issue-1282987627 you are saying that in an Isolated Function we should "treat" the function as a Console Application, like https://learn.microsoft.com/en-us/azure/azure-monitor/app/ilogger#console-application

Do we need to add an appsettings.json file (like a Console Application does) or not? Because the function itself does not have it "out of the box".
And put the logging configuration settings (like Log Level) in there? 

Is it possible to create an example Git repo for the different host/function Application Insights configurations in isolated mode?

**Comment by jviau** [comment] 2022-10-19 19:55
To get additional configuration sources, like `appsettings.json`, we can use this sample as starting point example: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Configuration/Program.cs#L20. From there we can add additional configuration sources like any other console app:

``` CSharp
var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults((IFunctionsWorkerApplicationBuilder workerApplication) =>
                {
                    // Use any of the extension methods in WorkerConfigurationExtensions.
                })
                .ConfigureAppConfiguration(cfg => cfg.AddJsonFile("appsettings.json"))
                .Build();
```

Alternatively, you can use this style to get several other defaults added:

``` CSharp
var host = Host.CreateDefaultBuilder()
                .ConfigureFunctionsWorkerDefaults((IFunctionsWorkerApplicationBuilder workerApplication) =>
                {
                    // Use any of the extension methods in WorkerConfigurationExtensions.
                })
                .Build();
```

With this approach be aware of the different defaults it will add. For example, console and event logging will be added. You may want to follow [this section](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging) to configure the different providers that will be added, potentially setting their default verbosity to `Critical` or so to prevent them from logging anything.

**Comment by emilssonn** [comment] 2022-10-20 12:41
@jviau 
I cannot get logging to work below the default level of Warning. I do not understand what is wrong with the configuration.

With the following setup only Warning, Error and Critical levels are logged in application insights when deployed to Azure, windows app service.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview3" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```
Program.cs:

```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder =>
    {
        builder
            .AddApplicationInsights()
            .AddApplicationInsightsLogger();
    })
    .ConfigureAppConfiguration((context, config) => config.AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, "appsettings.json"), optional: false, reloadOnChange: false))
    .Build();

host.Run();

```

Appsettings:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Information"
      }
    }
  }
}
```

Function:
```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace FunctionApp10
{
    public class Function1
    {
        private readonly ILogger _logger;
        private readonly IConfiguration _configuration;

        public Function1(ILogger<Function1> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }

        [Function("Function1")]
        public void Run([TimerTrigger("0 */1 * * * *")] MyInfo myTimer)
        {
            _logger.LogCritical("Default Loglevel: " + _configuration.GetValue<string>("Logging:ApplicationInsights:LogLevel:Default"));

            _logger.LogDebug("Log Debug");
            _logger.LogTrace("Log Trace");
            _logger.LogInformation("Log Info");
            _logger.LogWarning("Log Warn");
            _logger.LogError("Log Error");
            _logger.LogCritical("Log Critical");
        }
    }

    public class MyInfo
    {
        public MyScheduleStatus ScheduleStatus { get; set; }

        public bool IsPastDue { get; set; }
    }

    public class MyScheduleStatus
    {
        public DateTime Last { get; set; }

        public DateTime Next { get; set; }

        public DateTime LastUpdated { get; set; }
    }
}
```

**Comment by jviau** [comment] 2022-10-20 16:39
For some reason application insights registers a [hard-coded warning filter](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L421) to their provider. You can remove it with the following code:

``` CSharp
services.Configure<LoggerFilterOptions>(options =>
            {
                LoggerFilterRule toRemove = options.Rules.FirstOrDefault(rule => rule.ProviderName
                    == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");

                if (toRemove is not null)
                {
                    options.Rules.Remove(toRemove);
                }
            });
```

**Comment by AltusBaard** [comment] 2022-10-21 02:51
> For some reason application insights registers a [hard-coded warning filter](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L421) to their provider. You can remove it with the following code:
> 
> ```cs
> services.Configure<LoggerFilterOptions>(options =>
>             {
>                 LoggerFilterRule toRemove = options.Rules.FirstOrDefault(rule => rule.ProviderName
>                     == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");
> 
>                 if (toRemove is not null)
>                 {
>                     options.Rules.Remove(toRemove);
>                 }
>             });
> ```
> 
> Make sure this is ran _after_ adding app insights to the service collection.

Thanks @jviau, made use of this solution this morning to get our information logs to work, any idea if there is going to be a fix from MS for this?

**Comment by jviau** [comment] 2022-10-21 17:20
I wouldn't say there is anything to "fix". It is a choice the appinsights team made - wether we agree with it or not. In the end consumers of the appinsights SDK are not blocked from customizing it - the extensibility of the logging API is working as intended here (the end application is ultimately in full control and can undo/adjust what other packages have configured). You can also solve it via JSON configuration I believe. Something like:

``` JSON
{
  "Logging": {
    "ApplicationInsights": {
    "LogLevel": {
      "": "Information"
      }
    }
  },
}
```

**Comment by sergesountsov** [comment] 2022-10-21 18:19
> You can also solve it via JSON configuration I believe. Something like:
> 
> ```json
> {
>   "Logging": {
>     "ApplicationInsights": {
>       "LogLevel": {
>         "": "Information"
>       }
>     }
>   },
> }
> ```
This 👆 definitely does not work. This 👇does not work either
```json
    "Logging": {
        "ApplicationInsights": {
            "LogLevel": {
                "Default": "Information"
            }
        }
    }
```

**Comment by jviau** [comment] 2022-10-24 16:48
Ah I guess their comment is incorrect then. Looks like they have some issues regarding this already: https://github.com/microsoft/ApplicationInsights-dotnet/issues/2610. Feel free to leave a comment there asking them to change this behavior. But that is outside of our repo's scope.

Do you need any additional assistance with the original issue here?

**Comment by sergesountsov** [comment] 2022-10-24 18:17
The only way to get isolated Azure Function to log Information/Trace etc. to AppInsights is the rather ugly hack mentioned in (https://github.com/Azure/azure-functions-dotnet-worker/issues/1123#issuecomment-1286389808). None of the suggested configuration changes seem to work. If you feel that this is the way to go and outside of scope for current repo, I guess I'll stick with it.

**Comment by jviau** [comment] 2022-10-24 20:13
Unfortunately, it is out of scope for our repo. Even though I agree it is not an ideal scenario and the workaround isn't pretty, we do not own that code and is not our place to change it. However, we do have plans to improve our telemetry experience all up, which includes supported OpenTelemetry SDK. Their AzureMonitor exporter (which is what you would use to send to AppInsights in the OTel SDK world) may address this.

Closing this issue as per the discussion above.

**Closed by jviau** 2022-10-24 20:13 UTC
Labels: Needs: Author Feedback, logging

**Comment by emilssonn** [comment] 2022-10-25 11:40
@jviau @sergesountsov Am I missing something or, when I remove the hard-coded filter the default becomes information with no way to override by config?

The following still writes information logs from "Microsoft.EntityFrameworkCore.Database.Command".
```
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.EntityFrameworkCore.Database.Command": "Warning"
      "<category where I use ef>": "Information"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Warning",
        "Microsoft.EntityFrameworkCore.Database.Command": "Warning",
        "<category where I use ef>": "Information"
      }
    }
  },
```

**Comment by jviau** [comment] 2022-10-25 16:45
It is possible there are other configuration sources overriding your values, or these values are not actually brought in (maybe it isnt set to copy to output or something like that). I recommend debugging and examining `LoggerFilterOptions` after it is fully built (can import it to some service via `IOptions<LoggerFilterOptions>`) and checking what the final filters are.

**Comment by emilssonn** [comment] 2022-10-26 07:53
If anyone has the same problem. If you use `new HostBuilder()` and not `Host.CreateDefaultBuilder()` you also need to add the following:
```
.ConfigureLogging((hostingContext, logging) =>
    {
        logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
    })
```

**Comment by source-studio** [comment] 2022-11-03 11:25
Just to add to the conversation - the method I used to solve this problem was to manually configure the default Application Insights log level [via code](https://learn.microsoft.com/en-us/azure/azure-monitor/app/ilogger#create-filter-rules-in-code), rather than using an external settings file, which ultimately provided quite a clean solution.

For example, to change the default log level to `Information`:

```csharp
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder => builder
        .AddApplicationInsights()
        .AddApplicationInsightsLogger())
    .ConfigureLogging(logging => logging
        .AddFilter<ApplicationInsightsLoggerProvider>(null, LogLevel.Information))
    .Build();
```

**Comment by stevelknievel76** [comment] 2022-11-09 13:42
> If anyone has the same problem. If you use `new HostBuilder()` and not `Host.CreateDefaultBuilder()` you also need to add the following:
> 
> ```
> .ConfigureLogging((hostingContext, logging) =>
>     {
>         logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
>     })
> ```

I have the same issue.  After applying the hack provided by @jviau the default has become Information with no way to override.  Could you explain exactly how the above fixes this?  Maybe I didn't understand fully how to combine the 2.  I have the following:

```
                var host = new HostBuilder()
                    .ConfigureFunctionsWorkerDefaults(
                    builder =>
                    {
                        builder.AddApplicationInsights().AddApplicationInsightsLogger();
                    }
                    )
                    .ConfigureServices(serviceProvider =>
                    {
                        serviceProvider.Configure<LoggerFilterOptions>(options =>
                        {
                            var toRemove = options.Rules.FirstOrDefault(rule => rule.ProviderName
                                == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");

                            if (toRemove is not null)
                            {
                                options.Rules.Remove(toRemove);
                            }
                        });
                    })
                    .ConfigureLogging((hostingContext, logging) =>
                    {
                        logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    })
                    .Build();

```
