### ISSUE TITLE
Visual Studio 2019 debugging hangs when using RunOnStartup = true

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-functions-dotnet-worker#514] opened 2021-06-24 05:47 UTC
I have a very basic Azure functions project that I migrated to .Net 5 recently.
I was using RunOnStartup = true to trigger the TimerTriggered functions locally for debugging.

Now, after the upgrade VS fails to launch the debugger and hangs

![image](https://user-images.githubusercontent.com/8835012/123208681-2c3d2e00-d4dd-11eb-8469-4b90b6d42b22.png)

VS hangs while launching the debugger
![image](https://user-images.githubusercontent.com/8835012/123208727-3fe89480-d4dd-11eb-925b-aaebfa5caef8.png)

Cannot start the worker process
![image](https://user-images.githubusercontent.com/8835012/123208704-35c69600-d4dd-11eb-86c4-a0b5cf49cf3d.png)

Removing RunOnStartup = true resolves the problem and timer trigger works as per schedule
![image](https://user-images.githubusercontent.com/8835012/123208917-83430300-d4dd-11eb-91ca-c7dc058a6acf.png)

**Function**
```cs
       [Function("ResourceOperations")]
        public async Task RunAsync([TimerTrigger("*/5 * * * *", RunOnStartup = true, UseMonitor = false)] MyInfo myTimer, FunctionContext context)
        {
            var logger = context.GetLogger("ResourceOperations");
            logger.LogInformation($"ResourceOperations function executed at: {DateTime.UtcNow}");
            //logger.LogInformation($"Next timer schedule at: {myTimer.ScheduleStatus.Next}");

            await _resourceOperationsService.DeleteExpiredResourcesAsync();
        }

```
Configuration
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />

    <PackageReference Include="AzureEssentials.AzureResourceManager" Version="1.0.6" />
    <PackageReference Include="AzureEssentials.AzureTables" Version="1.0.3" />
    <PackageReference Include="AzureEssentials.MicrosoftGraph" Version="1.0.0" />
    <PackageReference Include="AzureEssentials.SendGrid" Version="1.0.0" />
    <PackageReference Include="IEvangelist.Azure.CosmosRepository" Version="2.1.9" />

    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="4.4.0" />

    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventGrid" Version="2.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Grpc" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.3.0" />

    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.8" />
    <PackageReference Include="Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.37.1" />
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.37.1" />
  </ItemGroup>
```

**Comment by brettsam** [comment] 2021-06-24 14:47
Closing as dupe of #434. Currently working on a fix.

**Closed by brettsam** 2021-06-24 14:47 UTC
Labels: Needs: Triage (Functions)
