### ISSUE TITLE
Adding Custom Dimensions Isn't Working In Telemery Initializers & Processors

### ISSUE THREAD

**Issue by ilkayilknur** [Azure/azure-functions-dotnet-worker#1067] opened 2022-09-27 14:13 UTC
I'm using the `Microsoft.Azure.Functions.Worker.ApplicationInsights-preview2` package and trying to send custom dimensions with the telemetry. I can see that the telemetry processor is triggered in my local environment, but when I publish the function app, I can't see the custom dimensions in application insights. I tested both telemetry initializers and processors, and it didn't work.

Telemetry Processor Code
```csharp
public class TelemetryProcessor : ITelemetryProcessor
    {
        private ITelemetryProcessor _next;

        public TelemetryProcessor(ITelemetryProcessor next)
        {
            _next = next;
        }

        public void Process(ITelemetry item)
        {
            var supportProperties = item as ISupportProperties;
            supportProperties.Properties["sampleProperty"] = "sampleValue";
            _next.Process(item);
        }
    }
```

Program.cs
```csharp
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(app =>
    {
        app.AddApplicationInsights()
                         .AddApplicationInsightsLogger();

        app.Services.AddApplicationInsightsTelemetryProcessor<TelemetryProcessor>();
    })
    .Build();

host.Run();
```
I'm not sure if custom dimensions are supported in this package. Is there a way to send custom dimensions in the isolated approach>

**Comment by brettsam** [comment] 2022-09-28 18:31
There's not much magic that happens here -- the worker is simply using the [Application Insights for Worker Services SDK](https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service). So, to debug this, can I have you check a couple of things?

1. Do you have APPLICATIONINSIGHTS_CONNECTION_STRING set as an app setting on the application?
2. Are you seeing telemetry, but just not these custom properties?
3. When you run this locally, using a real connection string, do the custom dimensions show up in App Insight?

**Comment by ilkayilknur** [comment] 2022-09-29 13:16
After further investigation, I saw that Exception telemetries aren't captured by the initializers.
See the custom dimension `sampleProperty:sampleValue`
![image](https://user-images.githubusercontent.com/5785927/193041173-61652dd1-39a1-45bc-8469-539a546c150e.png)

When I open the exception detail, the custom dimension isn't there.
![image](https://user-images.githubusercontent.com/5785927/193041266-ff36d52d-9ecd-44a3-8816-0b115b8bb730.png)

**Comment by im-yholota** [comment] 2022-11-11 15:58
@brettsam Does that mean that currently you cannot attach a processor or initializer for telemetry from an isolated process during startup?

**Comment by jviau** [comment] 2023-06-21 22:03
@im-yholota , you _can_ use processors or initializers, but that telemetry items they cover is different in the dotnet isolated scenario. The host and worker are now separate processes, and you can only adjust/enrich telemetry from the worker process.

Closing this as "by design"

**Closed by jviau** 2023-06-21 22:03 UTC
Labels: application-insights
