### ISSUE TITLE
WEBSITE_CLOUD_ROLENAME environment variable is not respected in Microsoft.Azure.Functions.Worker.ApplicationInsights package

### ISSUE THREAD

**Issue by DaRosenberg** [Azure/azure-functions-dotnet-worker#1708] opened 2023-07-02 11:04 UTC
The new `Microsoft.Azure.Functions.Worker.ApplicationInsights` preview package solves a lot of issues around using Application Insights in isolated worker function apps. 👍

One thing that still seems to be missing (inconsistent with the behavior of the function host) is respecting the `WEBSITE_CLOUD_ROLENAME` env variable for customization of what shows up on the application map in Application Insights.

The function host respects this env variable, but the configuration created by the `IFunctionsWorkerApplicationBuilder.AddApplicationInsights()` method added by this package does not. This results in inconsistent telemetry in Application Insights, where the function invocation is logged using the customized cloud role name, but any telemetry sent by the isolated worker (such as dependencies, custom metrics, etc) is logged using the default cloud role name (inferred from the function app name).

**Comment by jviau** [comment] 2023-07-06 22:51
Thank you for reporting this. While we are adding AppInsights support for the dotnet isolated process, it is not our goal to be a 1 to 1 match with the in-proc experience in this area. Instead, our intentions are to follow OpenTelemetry guidance.

We will evaluate if this fits with our vision for AppInsights for the worker or not. In the meantime, you can include your own copy of the [ITelemetryInitializer](https://github.com/Azure/azure-webjobs-sdk/blob/4d053ab5b4316d768166dbd10c9b531b2bfeb174/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsRoleEnvironmentTelmetryInitializer.cs#L22) which does this.

**Comment by DaRosenberg** [comment] 2023-07-07 10:25
@jviau Indeed that is the temporary workaround we put in place until you guys fix this (if you decide to do so). Thanks!

**Comment by fabiocav** [comment] 2023-07-12 20:24
Duplicate of #1634 

This is being addressed as part of #1634

**Closed by fabiocav** 2023-07-12 20:24 UTC
Labels: Needs: Triage (Functions), application-insights
