### ISSUE TITLE
ServiceBusOutput does not seem to pass on a value assigned to Correlation ID

### ISSUE THREAD

**Issue by Dave-Kiwi** [Azure/azure-functions-dotnet-worker#500] opened 2021-06-11 23:20 UTC
I am trying to get a ServiceBusOutput working on a Net 5 isolated function, where then output message needs a correlation ID assigned to it. Simple example of the code below. It appears that the Correlation ID is not being passing correctly out of the Function, so my listening subscriptions do not pick it up. Of course, this is stopping us transitioning to Net 5. Am I doing something wrong, or is there another way to set the correlation ID?

`        using Azure.Messaging.ServiceBus;
         using Microsoft.Azure.Functions.Worker;

        [Function(nameof(LameFunction1))]
        [ServiceBusOutput("topicname" Connection = "ServiceBusConnection")]
        public ServiceBusMessage Run([TimerTrigger("0 * * * * *")] TimerInfo timerInfo,
            FunctionContext inContext)
        {
            var myLogger = inContext.GetLogger(nameof(LameFunction1));

            var myResultMessage = new ServiceBusMessage("HELLO!")
            {
                CorrelationId = "pipeline-step-complete"
            };

            return myResultMessage;
        }`

**Comment by SeanFeldman** [comment] 2021-06-12 16:41
You can't use SDK type. I suspect you need to return a custom object with a property names `CorrelationId` for this to work but there's no info on the details.

@fabiocav could you point in the right direction? I don't mind to PR documentation to capture it. Thanks.

**Comment by Dave-Kiwi** [comment] 2021-06-13 03:05
I guess this is similar (or maybe the same as?) #474. If so, sorry for the duplicate.

**Comment by anthonychu** [comment] 2021-06-15 21:23
Looks like a dupe of #474.

**Closed by anthonychu** 2021-06-15 21:23 UTC
Labels: Needs: Triage (Functions)
