### ISSUE TITLE
Header added by middleware lost if HttpTrigger has POCO return type instead of HttpResponseData

### ISSUE THREAD

**Issue by pcrawtraffk** [Azure/azure-functions-dotnet-worker#1241] opened 2022-12-17 02:42 UTC
Using the sample in here
https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/CustomMiddleware/HttpFunction.cs

If I modify to add an additional HttpTrigger definition that returns a POCO.
```
    public class HttpFunction
    {
        [Function(nameof(HttpFunction2))]
        public static Response HttpFunction2([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequestData req, FunctionContext context)
        {
            var logger = context.GetLogger<HttpFunction>();

            // Get the item set by the middleware
            if (context.Items.TryGetValue("middlewareitem", out object value) && value is string message)
            {
                logger.LogInformation("From middleware: {message}", message);
            }
             return new Response();
        }
        public class Response
        {
            public string Description { get; set; } = "This is a response";
        }
    }
```

When executing the new function x-correlationId is not appended to the header.  When executing the old function that returns HttpResponseData, x-correlationId is appended.  How is it possible to return a POCO and still have middle modify the response headers?

**Comment by kshyju** [comment] 2022-12-19 17:39
This behavior is by design. You either need to return `HttpResponseData` or a type which has a property of type `HttpResponseData` (see sample [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/CustomMiddleware/HttpTriggerWithMultipleOutputBindings.cs#L14))

**Comment by kshyju** [comment] 2023-01-03 19:50
Closing as answered.

**Closed by kshyju** 2023-01-03 19:50 UTC
