### ISSUE TITLE
Microsoft.Azure.Functions.Worker.Sdk 1.16.0 generated code causing analyzer warnings

### ISSUE THREAD

**Issue by johan-lindqvist** [Azure/azure-functions-dotnet-worker#2060] opened 2023-11-14 08:35 UTC
Microsoft.Azure.Functions.Worker.Sdk 1.16.0 is giving analyzer warnings in the generated code.

Multiple elements such as:
```
Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionMetadataProviderGenerator/GeneratedFunctionMetadataProvider.g.cs(54,21): error CS1591: Missing XML comment for publicly visible type or member 'FunctionMetadataProviderAutoStartup.Configure(IHostBuilder)' [Microsoft.Azure.Functions.Worker.Sdk](https://togithub.com/Azure/azure-functions-dotnet-worker)
```

```
Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionMetadataProviderGenerator/GeneratedFunctionMetadataProvider.g.cs(52,18): error CS1591: Missing XML comment for publicly visible type or member 'FunctionMetadataProviderAutoStartup'
```

Other elements that are generating the same error:
```
WorkerHostBuilderFunctionMetadataProviderExtension

GeneratedFunctionMetadataProvider.GetFunctionMetadataAsync(string)

GeneratedFunctionMetadataProvider

FunctionExecutorAutoStartup.Configure(IHostBuilder)

FunctionExecutorAutoStartup

FunctionExecutorHostBuilderExtensions
```

**Comment by kshyju** [comment] 2023-11-14 17:08
Duplicate of #2027

The latest version of `Microsoft.Azure.Functions.Worker.Sdk` package includes a fix for this. So please upgrade to version [1.16.2](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.2) or later. 

Feel free to open a new issue if you still run into issues after upgrading to the latest version.

**Closed by kshyju** 2023-11-14 17:08 UTC

**Comment by woutervanranst** [comment] 2023-12-05 06:13
I m getting a CS1003 in v1.16.3 in combination with NUnit.
Downgrading to v1.16.2 solved this. I will just leave this here and see whether other ppl bumped into it.

Somehow generating a '.' in code:
```
workerextensionsstartupcodeexecutor typeof(.WorkerExtensionStartupCodeExecutor)
```

**Comment by kshyju** [comment] 2023-12-05 06:28
@woutervanranst  We have released a new version of the Microsoft.Azure.Functions.Worker.Sdk which fixes this issue. Could you please upgrade to that version?

https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.4-preview1
