### ISSUE TITLE
Version 1.17.0 breaks Azure Function Core Tools Start function

### ISSUE THREAD

**Issue by mvanmeerten** [Azure/azure-functions-dotnet-worker#2282] opened 2024-02-13 09:08 UTC
### Description

After upgrading to v1.17.0, the start function of Azure Function Core Tools no longer works. The first time the project will build properly and start the function, but the second time I get the following error message:
**`Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2`**

This might have something to do with it finding a second `.csproj` in this path `\obj\Debug\net6.0\WorkerExtensions\WorkerExtensions.csproj`

Let me know if you require more information.

### Steps to reproduce

1. run `func start`
2. Stop the function
3. run `func start`
4. Observe the error

**Comment by ReschAndr** [comment] 2024-02-14 14:14
We have encountered the same behavior and it is blocking us from updating the Microsoft.Azure.Functions.Worker.Sdk package to 1.17.0

**Comment by ryanheath** [comment] 2024-02-15 15:47
We run into more or less the same problem.

We do `dotnet restore` accessing a private feed and `dotnet build --no-restore`.
After the upgrade the build fails trying to restore packages (because private feed). 

We see at restore time the project `WorkerExtensions.csproj` is not available yet.
This project is created at build time but that is too late for our separate `dotnet restore` step.

**Comment by mariotebest** [comment] 2024-02-16 08:25
Our Team has the same issue, we are blocked from updating to 1.17.0

**Comment by richardtallent-erm** [comment] 2024-02-16 14:51
I'm having the same problem with `func azure functionapp publish`.

I'm in the folder for the function app, but its .csproj file includes a project reference to a project in a sibling directory.

**Comment by martin-bmc** [comment] 2024-02-17 14:43
I have the same issue when running local. Doing a `dotnet clean` before every `func start` allows it to start.

**Comment by iant-vaa** [comment] 2024-02-27 15:40
This has also been raised as https://github.com/Azure/azure-functions-dotnet-worker/issues/2294 which has a PR against it.

**Comment by satvu** [comment] 2024-03-05 22:32
@mvanmeerten Does 1.17.2 resolve your issue? What version of core-tools are you using? And what is the last known working SDK version for your scenario?

**Comment by mariotebest** [comment] 2024-03-06 08:00
At least for us - 1.17.2 resolved our issue!

**Comment by satvu** [comment] 2024-03-06 19:38
Closing as resolved for now.

**Closed by satvu** 2024-03-06 19:38 UTC
Labels: bug, Needs: Author Feedback

**Comment by teyc** [comment] 2024-04-10 09:39
Duplicate of https://github.com/Azure/azure-functions-core-tools/issues/3594
