### ISSUE TITLE
Functions do not work when using the `dotnet-isolated:4-dotnet-isolated6.0` base image.

### ISSUE THREAD

**Issue by elliotchaim** [Azure/azure-functions-dotnet-worker#810] opened 2022-02-15 17:09 UTC
I'm trying to deploy an Azure Functions app (net6.0 isolated functions v4) to Azure (Linux P1v2 app service plan). the app is containerized with `mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0` base image. i'm deploying and see logs in deployment center showing that the image was downloaded and container started. but no functions have been found and i get this error notification in the azure portal:

```
Microsoft.Azure.WebJobs.Script: WorkerConfig for runtime: dotnet-isolated not found.
```

i can't find any docs whatsover around setting up deployments to azure for functions v4 aside from deploying straight from vs code using the extension (not what i want to do). im trying to setup deployment of a production application from CI/CD using terraform

thanks

**Comment by xtellurian** [comment] 2022-02-28 08:03
I'm running into a similar issue. Deploying a dotnet 6.0 functions project. The Azure resource (linux app) is created using Pulumi then the code is deployed with functions CLI `func azure functionapp publish`

**Comment by fabiocav** [comment] 2022-03-01 22:16
Adding @kshyju here, but we have a deployment that should be completing in the next couple of weeks that will address this issue.

Will keep this open until that is done, but in the meantime, you follow the guidance in [this comment](https://github.com/Azure/azure-functions-docker/issues/600#issuecomment-1043737426)

**Comment by jkdmyrs** [comment] 2022-03-04 20:26
I am experiencing the same issue, however, I am just running a `dotnet publish` and using the `AzureFunctionApp@1` Azure DevOps Pipelines task to deploy the net6 functions app to a Linux functions app in Azure. I'm not using docker so I do not have the ability to specify App Service images as suggested in the workaround referenced by @fabiocav's comment.

What is the guidance in this case?

**Comment by ihordyrman** [comment] 2022-03-07 06:12
We are facing this issue as well.
@fabiocav any updates on this?  The comment you've linked is more than two weeks old and the issue is still here.

**Comment by BinishPeter** [comment] 2022-03-07 08:33
I had same issue, I got it fixed by changing the linux-fx-version to DOTNET-ISOLATED|6.0
check [stackoverflow](https://stackoverflow.com/questions/69254014/how-to-change-linuxfxversion-in-azure-function-app) on how to set it

**Comment by jkdmyrs** [comment] 2022-03-08 15:15
I was able to resolve the issues on my end via [this comment](https://github.com/Azure/azure-functions-dotnet-worker/issues/556#issuecomment-1052117943) in issue #556.

Basically, I'm using Azure App Configuration with keyvault linked values, and the keyvault access policy did not exist. 

This exception is extremely generic and seems to be thrown for ANY startup issue. There is definitely a need for the logging/exception handling during isolated functions startup.

**Comment by fabiocav** [comment] 2022-03-09 21:18
@ihordyrman did the workaround in the comment I've linked to help address the issue? https://github.com/Azure/azure-functions-docker/issues/600#issuecomment-1043737426, if not, it would be a good idea to have a separate issue opened with your application details so we can take a closer look, as this may have a different root cause.

**Comment by kshyju** [comment] 2022-03-09 23:59
@ihordyrman Could you try deploying using [function core tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#publish) and see that makes a difference?

@elliotchaim The "_The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found_" error is caused by [this issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/608), which was originally fixed, but only for app service images. Now we[ fixed it for all images](https://github.com/Azure/azure-functions-docker/pull/611) and the deployment for that is in-progress. Will share an update here when it is done (hopefully in the next couple of days)

**Comment by drmathias** [comment] 2022-03-10 13:46
> @ihordyrman Could you try deploying using [function core tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#publish) and see that makes a difference?

Deploying with `func azure functionapp publish` seems to work. However deploying the resource with Bicep/ARM and then using the `AzureFunctionApp@1` Azure pipelines task to deploy the function app results in the error.

**Comment by fabiocav** [comment] 2022-03-23 20:28
Just wanted to provide an update here. The full deployment with updated images addressing this issue should complete this week. 

We'll close this issue with an update when that is done.

**Comment by tnsholding** [comment] 2022-03-28 14:37
Any updates on this? - really stuck on this one, and anxiously waiting for a fix...

**Comment by elliotchaim** [comment] 2022-04-21 08:06
I fixed this issue by changing the base image to `mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0-appservice`.

I only figured this out after finding some obscure documentation somewhere. Really need to improve the docs for this!

**Comment by kshyju** [comment] 2022-05-09 17:59
Deployment with the fix (for non-app service images) has been completed. The `Microsoft.AspNetCore.App` framework should be present in the `mcr.microsoft.com/azure-functions/dotnet-isolated:4` image now.

Let us know if you run into issues.

**Comment by kshyju** [comment] 2022-05-09 17:59
> I fixed this issue by changing the base image to `mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0-appservice`.
> 
> I only figured this out after finding some obscure documentation somewhere. Really need to improve the docs for this!

@elliotchaim You should be able to use the non app-service images now.

**Closed** 2022-05-16 22:00 UTC
Labels: Needs: Author Feedback, no recent activity
