### ISSUE TITLE
Problems with deployed Function App

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#367] opened 2021-03-26 16:41 UTC
@fabiocav 

I'm also dealing with this, unfortunately, and it is critical that I get these functions working ASAP. Any help would be greatly appreciated. 

I am not using RunOnStartup, although I did use it during testing prior to release.

I deployed via PowerShell / Azure CLI. I'm seeing:

![image](https://user-images.githubusercontent.com/6976360/112634385-e8b92200-8e10-11eb-823c-86c19cd14aec.png)

In Azure Portal, Under Configuration > Function runtime settings, my runtime version is ~3. 
Under Application Settings:

- `FUNCTIONS_WORKER_RUNTIME` is `dotnet-isolated` 
- `FUNCTIONS_EXTENSION_VERSION` is `~3`

Here's my .csproj:

    <Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <TargetFramework>net5.0</TargetFramework>
	  <LangVersion>preview</LangVersion>
      <AzureFunctionsVersion>v3</AzureFunctionsVersion>
	  <OutputType>Exe</OutputType>
      <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>	
      <Version>1.1.0</Version>
    </PropertyGroup>
    
    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>  
    
    <ItemGroup>
      <PackageReference Include="Auth0.AuthenticationApi" Version="7.6.0" />
      <PackageReference Include="Auth0.ManagementApi" Version="7.6.0" />
	  
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.12" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.0.1" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1" OutputItemType="Analyzer" />
	  <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0" />
	  <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />	
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.3" />
      <PackageReference Include="Scrutor" Version="3.3.0" />
      <PackageReference Include="SendGrid" Version="9.22.0" />
      <PackageReference Include="Twilio" Version="5.55.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Keystone.Core\Keystone.Core.csproj" />
      <ProjectReference Include="..\Keystone.Data\Keystone.Data.csproj" />
      <ProjectReference Include="..\Keystone.Logic\Keystone.Logic.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Update="host.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="local.settings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>Never</CopyToPublishDirectory>
      </None>
    </ItemGroup>
  </Project>

_Originally posted by @kinetiq in https://github.com/Azure/azure-functions-dotnet-worker/issues/337#issuecomment-808194531_

**Comment by fabiocav** [comment] 2021-03-26 16:47
@kinetiq can you please provide your Invocation ID, Timestamp, and Region?  That will allow us to look up your Function App/Function. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**Comment by kinetiq** [comment] 2021-03-26 19:34
@fabiocav I'm ok with sharing the name of the functions app, in this case. 

- Name: https://keystonefuncs.azurewebsites.net
- Location: East US

Hopefully that gets you there. Thanks!

**Comment by fabiocav** [comment] 2021-03-26 21:53
@kinetiq would you mind opening the portal, navigating to the Function App, clicking on the `Functions` option (to view the functions) then clicking on the `refresh` button across the top? We'd like to validate the trigger synchronization flow and this should issue a request and would help us analyze that.  Thanks!

**Comment by kinetiq** [comment] 2021-03-27 00:19
Ok - I did it, but I don't see any changes. Because of that, I clicked it a few times.

This is what I clicked:

![image](https://user-images.githubusercontent.com/6976360/112704332-9e678d80-8e70-11eb-9590-32ded1fb273f.png)

**Comment by kinetiq** [comment] 2021-03-28 20:40
So it looks like these functions are running... However, I just got an email from one that ran today at 4:30 EST that normally runs in the evening.

**Comment by kinetiq** [comment] 2021-03-29 15:02
As  quick update here, the timer triggers are running very erratically. It seems like they might be running when I go into the portal in azure, which is quite bizarre.

**Comment by fabiocav** [comment] 2021-03-29 18:25
Yeah, the behavior you're seeing is consistent with what I'd expect as I'm seeing some issues with the trigger metadata in the scale controller (the component responsible for activation and scaling).

@ankitkumarr this is one of the issues I've mentioned. Trigger metadata doesn't seem to be correctly set, so the controller is not activating the app.

@kinetiq we'll continue to provide updates as we investigate.

**Comment by kinetiq** [comment] 2021-03-29 19:14
@fabiocav Thanks for the update. Do you have a sense that this will be resolved in days, or will it be more like weeks? I need to determine whether we need to fail back to our old code base.

**Comment by ankitkumarr** [comment] 2021-03-29 20:21
I took a look at this, and I think this is caused by a sync triggers issue that we had fixed some time back. The impact is limited to Windows function apps. Deploying this to a Linux function app should work as expected.

The fixed Azure Functions runtime is mid-deployment right now. The deployment should finish across all regions sometime this week. Once it's completed, I believe these issues should go away.

**Comment by fabiocav** [comment] 2021-03-29 20:28
OK, this this is part of the payload that is currently in progress? 

If so, @kinetiq , you can follow https://github.com/Azure/app-service-announcements/issues/323 for updates. We do expect deployment to be done this week.

**Comment by kinetiq** [comment] 2021-03-29 21:38
Great news. We can deal with it being good to go this week. Thanks for all the updates, I appreciate all of your help @ankitkumarr @fabiocav

**Comment by ankitkumarr** [comment] 2021-04-02 18:03
@kinetiq, the deployment has finished. Would you mind please retrying and letting us know if you continue to see these issues? Thank you!

**Comment by kinetiq** [comment] 2021-04-06 16:59
@ankitkumarr Looks like it worked! Thanks for keeping me up to date on this.

**Closed** 2021-04-13 22:01 UTC
Labels: Needs: Author Feedback, needs-investigation, no recent activity
