### ISSUE TITLE
How do I restart the func host on build automatically?

### ISSUE THREAD

**Issue by justinmchase** [Azure/azure-functions-dotnet-worker#840] opened 2022-03-24 20:15 UTC
I'm running:

```sh
dotnet watch build
```
```sh
func host start
```

But the func host is not reloading my functions after changes. How do I have it restart automatically after I make a change? 

My goal is:

1. Edit a C# file
2. Save
3. Boom Done

**Comment by fabiocav** [comment] 2022-03-29 21:16
This is not currently supported, but flagging as a request.

**Comment by fabiocav** [comment] 2022-03-29 21:20
Duplicate of #835

Closing this as a duplicate, but we'll be following up in the next tooling sync to understand the scope of the work.

**Closed by fabiocav** 2022-03-29 21:20 UTC
Labels: enhancement

**Comment by fabiocav** [comment] 2022-03-29 21:21
Closing this as a duplicate, but we'll be following up in the next tooling sync to understand the scope of the work.

**Comment by justinmchase** [comment] 2022-03-30 02:22
I was able to solve this by adding this to my csproj...

```xml
  <Target Name="RunFunctions" >
    <Exec Command="func host start" />
  </Target>
```

And then run
```sh
dotnet watch msbuild -t:RunFunctions
```
