### ISSUE TITLE
[BUG] with TimerTrigger and library System.Memory.Data, Version=6.0.0.0

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-functions-dotnet-worker#2886] opened 2024-12-03 17:06 UTC
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#47396](https://github.com/Azure/azure-sdk-for-net/issues/47396).

### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.Timer 4.3.1

### Describe the bug

I created empty azure function, dotnet 9, dotnet-isolated, I tried to add timer from library Microsoft.Azure.Functions.Worker.Extensions.Timer. 
Every time that I run this function there is an error.
The listener for function 'abc' was unable to start. Azure.Core: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, ...' the system cannot find the file specified.

When I replaced by Http trigger everything works fine.

I tried different approaches to Include library with version 6.0.0, addition of _FunctionsSkipCleanOutput, but nothing works

### Expected behavior

Function should be executed without any errors with TimerTrigger

### Actual behavior

Function throws an error after exectuin with TimerTrigger

### Reproduction Steps

Create Azure function, dotnet-isolated, .net 9, add latest libraries Microsoft.Azure.Functions.Worker.
Add TimerTrigger to example function with some code.

### Environment

.net 9
Dotnet-isolated 
Visual Studio 2022 17.12.1

**Comment by fabiocav** [comment] 2024-12-04 00:13
Duplicate of #10575

@MikeP707 please use the issue above for further updates.

**Closed by fabiocav** 2024-12-04 00:13 UTC
Labels: Needs: Triage (Functions)
