### ISSUE TITLE
Build failing with not being able to restore workerExtension.csproj

### ISSUE THREAD

**Issue by Ashwad1996** [Azure/azure-functions-dotnet-worker#2722] opened 2024-09-19 15:41 UTC
### What version of .NET does your existing project use?

.NET 6

### What version of .NET are you attempting to target?

.NET 8

### Description

Hi, We have recently moved to .Net8 isolated from .Net 6. We are encountering a transient error in our cloud build pipeline. When attempting to restore packages for our Azure Function, we receive the following errors:

```
D:\dbs\sh\aac6\temp\0mjoggt1.c2j\WorkerExtensions.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
D:\dbs\sh\aac6\temp\0mjoggt1.c2j\WorkerExtensions.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
D:\dbs\sh\aac6\temp\0mjoggt1.c2j\WorkerExtensions.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.js
on.
```

We tried the hack mentioned in https://github.com/Azure/azure-functions-dotnet-worker/issues/1252 to create a separate project and add the required dependencies, and it worked. However, the problem has resurfaced in the past two weeks. The error is inconsistent—sometimes it automatically resolves itself, but other times the build fails. Could someone please assist us with this issue? 

### Project configuration and dependencies

```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" />
<PackageReference Include="Microsoft.Azure.Kusto.Ingest" />
<PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" />
<PackageReference Include="Microsoft.Extensions.Http.Polly" />
<PackageReference Include="Microsoft.FeatureManagement" />
<PackageReference Include="Microsoft.Identity.ServiceEssentials.AspNetCore" />
<PackageReference Include="Microsoft.Identity.ServiceEssentials.Standard" />
<PackageReference Include="Microsoft.Identity.ServiceEssentials.TokenAcquisitionIdWeb" />
<PackageReference Include="OpenTelemetry.Exporter.OneCollector" />
<PackageReference Include="System.CodeDom" VersionOverride="8.0.0" />
<PackageReference Include="Microsoft.VisualStudio.Services.Release.Client" />
<PackageReference Include="Microsoft.TeamFoundation.DistributedTask.WebApi" />
<PackageReference Include="Microsoft.TeamFoundationServer.Client" />
<PackageReference Include="System.Formats.Asn1" />
<PackageReference Include="YamlDotNet" VersionOverride="6.1.2" />
<PackageReference Include="OpenTelemetry.Exporter.Geneva" VersionOverride="1.8.0" />
<PackageReference Include="Serilog.Sinks.Console" />
<PackageReference Include="Serilog.Extensions.Logging" />
<PackageReference Include="Serilog.Sinks.ApplicationInsights" />
<PackageReference Include="StringTokenFormatter" />
<PackageReference Include="System.Net.Http" VersionOverride="4.3.4" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" VersionOverride="1.17.2" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" VersionOverride="3.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" VersionOverride="2.2.0" />
<PackageReference Include="Grpc.Net.ClientFactory" VersionOverride="2.63.0" />
```

### Link to a repository that reproduces the issue
https://o365exchange.visualstudio.com/O365%20Core/_git/DeploymentStd1B

_No response_

**Comment by keyurtechy** [comment] 2024-09-19 21:55
Please update the 
1) "Microsoft.Azure.Functions.Worker" Version="1.23.0"
2) Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.4" 

This should build the projects. I was facing the same issue

**Comment by nvmkpk** [comment] 2024-09-20 20:16
I ran into this issue in the pipelines after updating `Microsoft.Azure.Functions.Worker.Sdk` from version `1.15.1` to version `1.17.4`. It worked locally just failed in the pipelines. I had to downgrade to version `1.16.4` to fix it.

**Comment by Ashwad1996** [comment] 2024-09-24 08:55
After following these steps, two out of the three errors have been resolved, but one still remains. Any other suggestion?

**Comment by jviau** [comment] 2024-11-13 18:26
Closing this as we have an existing issue.

Duplicate of #1252

**Closed by jviau** 2024-11-13 18:26 UTC
Labels: Needs: Triage (Functions), area: migration
