### ISSUE TITLE
Using byte[] input binding type for azure function service bus trigger in batch de-queue mode

### ISSUE THREAD

**Issue by BijanSafai** [Azure/azure-functions-dotnet-worker#1141] opened 2022-10-20 18:00 UTC
My team and I have been developing an azure functions based service leveraging the service bus trigger extension.

The messages we are dequeuing from the service bus have been compressed so we deque them as byte[] (as specified in the docs here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=isolated-process%2Cextensionv5&pivots=programming-language-csharp). This is working fine with non-batched triggers such as the provided example:

```
public static async Task <Service Bus Trigger>(
        [ServiceBusTrigger(<Service Bus Name>, Connection = "ServiceBusConnection", IsSessionsEnabled = true)]
            byte[] message,
            string messageId,
            string correlationId)
```
As part of our optimization effort we have been trying to experiment with triggers in batch delivery mode, such as the below example:

```
        public static async Task <Service Bus Trigger>(
            [ServiceBusTrigger(<Service Bus Name>, Connection = "ServiceBusConnection", IsSessionsEnabled = true, IsBatched = true)]
            IEnumerable<byte[]> messages)
```
While this trigger does execute when messages are enqueued onto the bus the "messages" parameter is always null. This behavior does not occur if we instead input bind to a collection strings:

```
        public static async Task <Service Bus Trigger>(
            [ServiceBusTrigger(<Service Bus Name>, Connection = "ServiceBusConnection", IsSessionsEnabled = true, IsBatched = true)]
            IEnumerable<string> messages)
```
In this case the collection is populated. I'm wondering if this is expected behavior and batch delivery simply does not support input binding into a collection of byte arrays or if there is some extra configuration needed to support it that we are missing.

**Comment by BijanSafai** [comment] 2023-01-04 23:37
Pinging on this issue again, any insights to share?

**Comment by soninaren** [comment] 2023-06-08 19:59
I attempted to reproduce the issue above. I created a function app referencing `Microsoft.Azure.Functions.Worker.Extensions.ServiceBus Version 5.7.0`. 

In my case i observed that the function was triggered when i used the `IEnumberable<string>` the function triggered as expected and i was able to parse the byte array back to the original string
        `public void Run([ServiceBusTrigger("myq2", Connection = "con", IsSessionsEnabled = false, IsBatched = true)] IEnumerable<string> myQueueItems)`

However In case of `IEnumerable<byte>` the function did not trigger and i got the following exception.
```
System.Private.CoreLib: Exception while executing function: Functions.Function. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myQueueItems'. Microsoft.Azure.WebJobs.Host: Binding parameters to complex objects (such as 'Object') uses Json.NET serialization.
[2023-06-08T19:56:46.900Z] 1. Bind the parameter type as 'string' instead of 'Object' to get the raw values and avoid JSON deserialization, or
[2023-06-08T19:56:46.901Z] 2. Change the queue payload to be valid json. The JSON parser failed: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
```

**Comment by soninaren** [comment] 2023-06-08 20:36
There was an error in my attempted repro in the above comment. I should have used `IEnumerable<byte[]> myQueueItems` instead of `IEnumerable<byte> myQueueItems`. After making that change i was able to observe the same behavior. The function triggered with `myQueueItems` as null.

**Comment by satvu** [comment] 2023-07-11 23:42
The root cause is that we are missing a converter for this specific parameter type. Created #1734 to track logging work related to this, and leaving this issue open to track adding this converter. Before adding the converter, we would have to validate that this does not cause unexpected behavior for other scenarios aside from the ServiceBus trigger.

**Comment by satvu** [comment] 2023-10-18 21:19
Closing this as investigation is complete - #1967 will track the progress for adding the converter.

**Closed by satvu** 2023-10-18 21:19 UTC
Labels: bug, needs-investigation
