### ISSUE TITLE
Unable to override the JsonSerializer when using ConfigureFunctionsWebApplication

### ISSUE THREAD

**Issue by davidpetric** [Azure/azure-functions-dotnet-worker#2131] opened 2023-12-06 09:51 UTC
Hi,

I migrated from In process to .NET 8 Worker with AspNetCore integration and can't set the serializer to be Newtonsoft so I can keep old behavior for [FromBody] attribute.

What I've tried:

Option 1:

``` csharp
    .ConfigureFunctionsWebApplication(workerAppBuilder => workerAppBuilder.UseNewtonsoftJson())
```

Option 2:

``` csharp
  .ConfigureServices((context, services) =>{
  
    services.Configure<WorkerOptions>(workerOptions =>
    {
        JsonSerializerSettings settings = NewtonsoftJsonObjectSerializer.CreateJsonSerializerSettings();
        settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
        settings.NullValueHandling = NullValueHandling.Ignore;

        workerOptions.Serializer = new NewtonsoftJsonObjectSerializer(settings);
    }) 
    
    }|)
 ```
 
The exception I am getting is:

``` csharp
[2023-12-06T09:35:04.528Z] Function 'createOrUpdate', Invocation id '172f2590-9810-48b0-8fa7-bdb1b02b1ea6': An exception was thrown by the invocation.
[2023-12-06T09:35:04.530Z] Result: Function 'createOrUpdate', Invocation id '172f2590-9810-48b0-8fa7-bdb1b02b1ea6': An exception was thrown by the invocation.
Exception: System.InvalidOperationException: The JSON value could not be converted to System.Nullable`1[System.Guid]. Path: $.repeatIntervalUnitsId | LineNumber: 0 | BytePositionInLine: 27.
[2023-12-06T09:35:04.534Z]
[2023-12-06T09:35:04.536Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FromBodyConverstionFeature.ConvertAsync(FunctionContext context, Type targetType) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FromBodyConverstionFeature.cs:line 91
[2023-12-06T09:35:04.537Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.Converters.FromBodyConverter.HandleResultAsync(ValueTask`1 result) in D:\a\_work\1\s\extensions\Worker.Extensions.Http\src\FromBodyConverter.cs:line 28
[2023-12-06T09:35:04.548Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.AwaitAndReturnConversionTaskResult(ValueTask`1 conversionTask) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 103
[2023-12-06T09:35:04.549Z] Executed 'Functions.createOrUpdate' (Failed, Id=172f2590-9810-48b0-8fa7-bdb1b02b1ea6, Duration=343ms)
[2023-12-06T09:35:04.555Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.ConvertAsync(ConverterContext converterContext) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 43[2023-12-06T09:35:04.556Z] System.Private.CoreLib: Exception while executing function: Functions.createOrUpdateTask. System.Private.CoreLib: Result: Failure

```

**Comment by davidpetric** [comment] 2023-12-06 11:45
Was able to make the error go away:

1. Install Nuget: `Microsoft.AspNetCore.Mvc.NewtonsoftJson`

2. Add  `services.AddMvcCore().AddNewtonsoftJson();` in `ConfigureServices()`


But is this the right way of doing it? I am wondering if this will create issues..

**Comment by davidpetric** [comment] 2023-12-07 13:52
Anyone?

**Comment by simonholmandev** [comment] 2023-12-08 22:52
I'm keen to see an answer on this as well as NewtonsoftJson is required for the SendGrid integration to work correctly.

**Comment by davidpetric** [comment] 2024-02-15 09:28
> Was able to make the error go away:
> 
> 1. Install Nuget: `Microsoft.AspNetCore.Mvc.NewtonsoftJson`
> 2. Add  `services.AddMvcCore().AddNewtonsoftJson();` in `ConfigureServices()`
> 
> But is this the right way of doing it? I am wondering if this will create issues..

Hey,

I was wondering if you have any updates on whether this is a safe or recommended way of doing it. 

Thank you

**Comment by davidpetric** [comment] 2024-02-27 21:36
> I
> 
> > > Was able to make the error go away:
> > > 
> > > 1. Install Nuget: `Microsoft.AspNetCore.Mvc.NewtonsoftJson`
> > > 2. Add  `services.AddMvcCore().AddNewtonsoftJson();` in `ConfigureServices()`
> > > 
> > > But is this the right way of doing it? I am wondering if this will create issues..
> > 
> > 
> > Hey,
> > I was wondering if you have any updates on whether this is a safe or recommended way of doing it.
> > Thank you
> 
> I would be interested to hear too. I done the same thing you have done after trying a ton of different options. I take it you are using field annotations?
> 
> I haven't had any problems yet, so If it works it works I guess. Until there is a fix for the ConfigureFunctionsWebApplication Json Serializer this will have to do, wait for the PR.
> 
> Another other way I found was to remove the model binding and read the model in as asyncString, then serialize with Newtonsoft. I think the trick to getting it working with both worker and web is in the functionContext but I ran out of time.
> 
> Configuration of azure function apps in C# is a bit of a nightmare, documentation is all over the place. On the other hand, setting up one in JS/Typescript was a breeze.

I had to set up some converters for the System.Text.Json to keep the same behavior as the old "In-Process".

The actual setup works ok, but I wonder if it will break in the future because it may not be the intended way of using it that's why I am asking this question.

**Comment by maxpowernz** [comment] 2024-02-29 00:09
> > I
> > > > Was able to make the error go away:
> > > > 
> > > > 1. Install Nuget: `Microsoft.AspNetCore.Mvc.NewtonsoftJson`
> > > > 2. Add  `services.AddMvcCore().AddNewtonsoftJson();` in `ConfigureServices()`
> > > > 
> > > > But is this the right way of doing it? I am wondering if this will create issues..
> > > 
> > > 
> > > Hey,
> > > I was wondering if you have any updates on whether this is a safe or recommended way of doing it.
> > > Thank you
> > 
> > 
> > I would be interested to hear too. I done the same thing you have done after trying a ton of different options. I take it you are using field annotations?
> > I haven't had any problems yet, so If it works it works I guess. Until there is a fix for the ConfigureFunctionsWebApplication Json Serializer this will have to do, wait for the PR.
> > Another other way I found was to remove the model binding and read the model in as asyncString, then serialize with Newtonsoft. I think the trick to getting it working with both worker and web is in the functionContext but I ran out of time.
> > Configuration of azure function apps in C# is a bit of a nightmare, documentation is all over the place. On the other hand, setting up one in JS/Typescript was a breeze.
> 
> I had to set up some converters for the System.Text.Json to keep the same behavior as the old "In-Process".
> 
> The actual setup works ok, but I wonder if it will break in the future because it may not be the intended way of using it that's why I am asking this question.

Im just going to move away from Newtonsoft with isolated worker, looks like the push is to System.Text.Json, who knows what will come. The v4 cosmosdb worker package includes NewtonSoft.json, that should be taken out of there if its intended to be  opt in, why have it as a dependency? And im starting wonder if there is any real benefit in even using Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore, that makes you use ConfigureFunctionsWebApplication, which is were all the confusion is.

**Comment by fabiocav** [comment] 2024-04-03 20:32
@davidpetric we'll take a closer look at your issue before providing any additional guidance, as the requirement doesn't seem right.

@simonholmandev can you please open a separate issue for the SendGrid problem (with the stack/details) so we can take a closer look at that? Thanks!

**Comment by EmilDamsbo** [comment] 2024-04-30 20:09
I have been running into this too, and it's hindering my ability to do orchestration with polymorphic inputs. I used to use a Newtonsoft [SerialzationBinder](https://www.newtonsoft.com/json/help/html/SerializeSerializationBinder.htm) in NET6 and in-process model, where my orchestrator would accept polymorphic input.

Now, my types get pigeonholed, so if it's not an exact match then the parameter is null. Illustrated in this Gist:
https://gist.github.com/EmilDamsbo/616ba3bfa114719c5f41f90a0406a138

Not sure if it's the same underlying issue, but it's likely related

**Comment by patelriki13** [comment] 2024-05-02 05:16
Is any update on this? I also facing same issue.

and is any work around which proper?

**Comment by patelriki13** [comment] 2024-05-02 05:17
@fabiocav any update?
I also facing same issue. Recenty migrage .net 6 to .net 8 azure fuction.
Any workaround?

**Comment by Camios** [comment] 2024-05-09 00:32
Microsoft advised that .net 6 Function apps are going out of support in Nov 2024.
So I ran into this problem after running the .net Upgrade Assistant on a Function app project using in-process worker model on .net 6 to .net 8 isolated worker model.

I tried the sample https://github.com/Azure/azure-functions-dotnet-worker/blob/16a995deb65b44873cd3a56b5e6d4d3c22d64b7d/samples/Configuration/Program.cs to try and use Newtonsoft json serializers but it caused big problems. Depending on the order of calling the ConfigureFunctionsWorkerDefaults or ConfigureFunctionsWebApplication extension methods it either dead-locked or returned a 200 - neither approach actually calling my Function App's body.

You might get more of these problems being raised since .net 6 support is stopping. Might need to bump its priority?

**Comment by Camios** [comment] 2024-05-10 05:11
Quite frustrating when upgrading from .NET 6 to 8, being forced to migrate from Newtonsoft.Json to System.Text.Json to find the `Microsoft.Azure.Functions.Worker.CosmosDBConverter` has a hard-coded `JsonSerializerOptions` when deserializing.

**Comment by ulluoink** [comment] 2024-05-15 12:24
What is going on here? Why is this not fixed ? 

Using the ConfigureFunctionsWebApplication is the only way of dealing with http triggered functions.

Do you really want us to use the Microsoft json serializer? This is impossible!

We run from one problem to the next while changing to isolated-worker model. Which we are required to use if we ever want to upgrade to .net 8

Just fix this bug !

**Comment by ulluoink** [comment] 2024-05-15 13:25
when trying to use the documented way of using NewtonSoft as default Serializer this just does not work:
doing something like this in a http-triggered function:

return new OkObjectResult(myCustomObject);

will still use the System.Text.Json serializer.

link to microsoft documentation: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#customizing-json-serialization

**Comment by ulluoink** [comment] 2024-05-25 08:33
@liliankasem the issue is not only with [FromBody] but also if you use 

return new OkObjectResult(myCustomObject);

then also the System.Text.Json serializer is used.

i opened https://github.com/MicrosoftDocs/azure-docs/issues/122534 but there is nothing happening.

**Comment by Camios** [comment] 2024-05-27 00:06
It is also broken for Cosmos bindings

**Comment by patelriki13** [comment] 2024-05-27 03:54
Also broken HttpClient request serializer.

**Comment by liliankasem** [comment] 2024-05-28 17:31
Thanks for the responses here, if you could open other issues in this repo for any non `FromBody` related serialization problems that would be really helpful. Thank you.

**Comment by Tri125** [comment] 2024-05-29 19:31
I've noticed that modifying the serializer used by the worker will cause ``HttpResponseData.WriteAsJsonAsync`` to throw ``System.InvalidOperationException: 'Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.'`` and it will hang, leaving the client without any response.

```
// program.cs

using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using Azure.Core.Serialization;

var host = new HostBuilder()
    .ConfigureFunctionsWebApplication((IFunctionsWorkerApplicationBuilder builder) =>
    {
        builder.Services.Configure<WorkerOptions>(workerOptions =>
        {
            // Newtonsoft configuration.
            // By default System.Text.Json is used.
            var settings = NewtonsoftJsonObjectSerializer.CreateJsonSerializerSettings();
            settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            settings.NullValueHandling = NullValueHandling.Ignore;

            workerOptions.Serializer = new NewtonsoftJsonObjectSerializer(settings);
        });
    })
    .ConfigureServices((hostBuilderContext, services) =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .Build();

host.Run();

```
// Function1.cs

using Microsoft.AspNetCore.Http;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using FromBodyAttribute = Microsoft.Azure.Functions.Worker.Http.FromBodyAttribute;

namespace FunctionApp
{
    public class Dto
    {
        public string Name { get; set; }
    }

    public class Function1
    {
        [Function("Function1")]
        public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Anonymous, "post")] [FromBody] Dto input, HttpRequestData req)
        {
            var res = req.CreateResponse();

            // This will throw System.InvalidOperationException
            await res.WriteAsJsonAsync(new Dto
            {
                Name = "Test"
            });

            return res;
        }
    }
}

```

If I don't customize the serializer used by the worker inside `` .ConfigureFunctionsWebApplication()``, then there's no issue when using ``WriteAsJsonAsync()``

**Comment by fabiocav** [comment] 2024-05-29 21:55
Folks, we'll be sharing some guidance specific to the problem described in the original issue (serialization configuration using `FromBodyAttribute`). As we're getting a mix of other issues here, we're locking the issue to keep the conversation focused and ask that you open new issues if you have questions/problems with serialization configuration for different scenarios.

Thank you!

**Comment by fabiocav** [comment] 2024-07-09 00:05
Apologies for the delayed update here.

Just wanted to close out on this with guidance on how the integration works today.

When using the ASP.NET Core integration, the following will change the serializer used when handling JSON payloads:

``` csharp
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
        services.AddMvc().AddNewtonsoftJson();
    })
    .Build();
host.Run();
```

@ulluoink , the above is a simplified version of what @liliankasem had shared (functionally the same), hope that helps with the your comment above.

@Tri125 I've moved your comment to a different issue so we can track that separately.

Closing this as answered, but please let us know if you have any additional questions.

**Closed by fabiocav** 2024-07-09 00:05 UTC
Labels: needs-investigation, Needs: Triage (Functions), area: http
