### ISSUE TITLE
Azure.Messaging.ServiceBus: The lock supplied is invalid when function executes successfully

### ISSUE THREAD

**Issue by cosminstirbu** [Azure/azure-functions-dotnet-worker#1021] opened 2022-09-02 06:23 UTC
Hello,

We have an isolated .NET 6 Azure Function that consumes a service bus message and publishes two other messages to a different service bus namespace.

The issue is that even after the function finishes executing, as per the attached screenshot, `The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance. (MessageLockLost)` exception is thrown approx 20 seconds after the function finishes executing when the host / extension attempts to complete the message.

![Screenshot 2022-09-02 at 09 03 18](https://user-images.githubusercontent.com/7135690/188070725-7086f946-a96b-42f9-bc49-9f3ad5a5c86f.png)

This doesn't always reproduce, we've seen 5 occurrences in 7k function executions - however that's enough for us to at least investigate it.

P.S. - A few weeks ago I've logged a "similar" issue that occurs when the function throws an exception https://github.com/Azure/azure-functions-dotnet-worker/issues/1003 - approximately 20 seconds after the failed execution is logged, you can see an exception attempting to renew the lock.

These are the package versions we're using

```
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.4.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" />
```

Since the message completion fails, this can be a bit problematic, because it leads to the message being consumed twice or more.

**Comment by satvu** [comment] 2022-09-14 18:21
We're going to close this issue and consolidate the investigation on #1003 - we suspect the root cause is the same.

**Closed by satvu** 2022-09-14 18:21 UTC
Labels: needs-investigation
