### ISSUE TITLE
Kafka extension still fails with `Failed to load the librdkafka native library`

### ISSUE THREAD

**Issue by arkiaconsulting** [Azure/azure-functions-dotnet-worker#450] opened 2021-05-17 15:09 UTC
The issue #194 should have been resolved, but looks like it's not.

I can confirm that the build uses the right target (the one with #204 changes).

Nuget Configuration:
```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.2.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Kafka" Version="3.2.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
```

Core Tools Version:       3.0.3442
Function Runtime Version: 3.0.15417.0

Error:
`Confluent.Kafka: Failed to load the librdkafka native library`

**Comment by fabiocav** [comment] 2021-05-18 22:12
@arkiaconsulting what OS do you see this error in?

**Comment by arkiaconsulting** [comment] 2021-05-19 05:20
Hi @fabiocav ! Windows 10, local debug

**Comment by fabiocav** [comment] 2021-05-25 21:31
Assigning to the next sprint for investigation.

**Comment by fabiocav** [comment] 2021-06-09 20:11
Moving this to 104 as this wasn't addressed this sprint

**Comment by fabiocav** [comment] 2021-06-24 20:21
Adding @TsuyoshiUshio for visibility

Ankit is still investigating this, so moving to 105

**Comment by TsuyoshiUshio** [comment] 2021-06-25 07:52
Hi @arkiaconsulting
Do you use extension bundle? or install kafka extension it's self? 
If you are using extension bundle, for the mitigation, could you run `func host start --verbose`  then you will find the path of the extension bundle.  For windows,  You can specify `LIBRDKAFKA_LOCATION` environment variables for the mitigation. For more details, refer to https://github.com/Azure/azure-functions-kafka-extension/issues/247 .

**Comment by arkiaconsulting** [comment] 2021-06-25 12:04
@TsuyoshiUshio Hi, I'm not using extension bundles. The extension is install using the NuGet `Microsoft.Azure.Functions.Worker.Extensions.Kafka` (3.2.1).

Manually specifying the location using `LIBRDKAFKA_LOCATION=<_redacted_>\bin\Debug\net5.0\runtimes\win-x64\native` induces the error
```
Confluent.Kafka: Failed to load librdkafka at location '<_redacted_>\bin\Debug\net5.0\runtimes\win-x64\native'. Win32 error: 126.
```

**Comment by TsuyoshiUshio** [comment] 2021-06-25 23:28
Hi @arkiaconsulting 
You are looking at wrong directory, since it looks net5.0. Is it out of proc dotnet? 
Extension Bundle is located the different place. For example, In my case `set LIBRDKAFKA_LOCATION=C:\Users\tsushi\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\2.6.1\bin\runtimes\win-x64\native\librdkafka.dll` is the one solves. 

with `func host --verbose` you will find `[2021-06-25T22:35:24.787Z] Loading extension bundle from C:\Users\tsushi\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\2.6.1\bin` section, that is the place of the Kafka Extension with extension bundle.  for the LIBRDKAFKA_LOCATION, we need to add `runtimes\win-x64\native\librdkafka.dll`.

**Comment by arkiaconsulting** [comment] 2021-06-26 05:11
Hi @TsuyoshiUshio 
As I don't use extension bundles, I don't have the directory you mentioned under my home folder.

Anyway, I set the environment variable as following (this time with the dll explicitely):
```
LIBRDKAFKA_LOCATION=<_redacted_>\bin\Debug\net5.0\.azurefunctions\runtimes\win-x64\native\librdkafka.dll
```
The function now runs correctly.

Does that mean that the runtime is having hard times to find the dll by itself ?

**Comment by TsuyoshiUshio** [comment] 2021-06-26 12:59
It looks dotnet5 isolated issue.  The native library is created under `bin\output\.azurefunctions\runtimes\win-x64\native\librdkafka.dll`.   Also, I can find the `bin\output\.azurefunctions\function.deps.json` include librdkafka.dll native library. 
It should be loaded. 

Hi @ankitkumarr 
Do you know if it is the known issue? 

## Files 
I reproduced the issue with isolated environment. 
![image](https://user-images.githubusercontent.com/1390976/123513383-e0f06000-d641-11eb-9076-318f9c897b04.png)

## Note

https://github.com/Azure/azure-functions-host/blob/852eed9ceef6ef56b431428a8eb31f1bd9c97f3b/src/WebJobs.Script/Description/DotNet/FunctionAssemblyLoadContext.cs#L62

It looks, Initialize Dep file eventually looking at this place. However, It doesn't look at `bin/output/.azure-functions/functions.deps.json` . 
https://github.com/Azure/azure-functions-host/blob/852eed9ceef6ef56b431428a8eb31f1bd9c97f3b/src/WebJobs.Script/Description/DotNet/FunctionAssemblyLoadContext.cs#L523

**Comment by fabiocav** [comment] 2021-07-07 20:32
This is related to https://github.com/Azure/azure-functions-host/issues/6925 and should be addressed when that change takes place. That change is delayed, but we're making progress on that item and hoping to have that soon.

**Comment by fabiocav** [comment] 2023-06-16 23:54
@arkiaconsulting following up on stale issues and wanted to see if this issue is still impacting you. 

The change we were tracking has been deployed, so this should be resolved. If you can confirm, that would be great!

Thanks

**Comment by arkiaconsulting** [comment] 2023-06-17 06:21
@fabiocav thanks for following up. I couldn't say, we switched from Kafka to Service Bus some months ago.

**Comment by kshyju** [comment] 2023-12-06 00:02
Closing this issue as this is not valid anymore, as per the last update from OP.

**Closed by kshyju** 2023-12-06 00:02 UTC
Labels: Needs: Attention :wave:

**Comment by hmantri05** [comment] 2024-07-18 11:04
@fabiocav I have the same issue in my Azure Function App when I try to bring this up locally.

**Comment by kshyju** [comment] 2024-07-18 14:07
@hmantri05 / @nile649 Could you please open a new issue with relevant details and repro steps? Thanks!
