### ISSUE TITLE
AppInsights cloud role name property contains "-staging" post fix for all event types except for the "Request" event type

### ISSUE THREAD

**Issue by brewstertimothybrewster** [Azure/azure-functions-dotnet-worker#1680] opened 2023-06-23 12:22 UTC
We have a setup with Azure Function Isolated v4 running. This setup has also a staging deployment slot, which is started and used for testing during deployment, after a successful health check the staging slot is swapped with the production slot and short after the staging slot is stopped. However the "Role name" property within all the AppInsight logs seems to have the app name post fixed with "-staging", except for the "Request" event type, this contains the correct role name which is the app name. Is this a known bug? I know that you can set this "Role name" manualy with TelemetryInitializers, but this should be used if you don't want the default app name right?

**Comment by fabiocav** [comment] 2023-07-05 20:41
Duplicate of #1634

**Closed by fabiocav** 2023-07-05 20:41 UTC
Labels: Needs: Triage (Functions), logging
