### ISSUE TITLE
WorkerExtensionStartupCodeExecutor.g.cs: Type expected build error after upgrade to .NET 8

### ISSUE THREAD

**Issue by rodolfograve** [Azure/azure-functions-dotnet-worker#2126] opened 2023-12-05 14:59 UTC
Hi.

I have a solution where all projects are now targeting .NET 8.

1. A library project that references Microsoft.Azure.Functions.Worker (but not the SDK).
2. Two Azure Functions projects (Isolated) that reference project 1 above (these do reference Microsoft.Azure.Functions.Worker.Sdk)
3. A library project that references both Azure Function projects (this is for testing purposes)
4. A bunch of test projects that reference project 3 above.

This setup has been building OK for over a year. However, after upgrading to .NET 8, project 3 is not building. The error messages come from a generated file (.g.cs):

> ...\Local\Temp\tp02libj.cty\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.ExtensionStartupRunnerGenerator\WorkerExtensionStartupCodeExecutor.g.cs: Type expected
...\Local\Temp\tp02libj.cty\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.ExtensionStartupRunnerGenerator\WorkerExtensionStartupCodeExecutor.g.cs: ) expected
...\Local\Temp\tp02libj.cty\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.ExtensionStartupRunnerGenerator\WorkerExtensionStartupCodeExecutor.g.cs: Syntax error, ',' expected
...\Local\Temp\tp02libj.cty\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.ExtensionStartupRunnerGenerator\WorkerExtensionStartupCodeExecutor.g.cs: Identifier expected

I have not been able to reproduce this creating the projects from scratch, but I'm hoping someone from the team can use the fact that it was building before and that the errors come from generated files to give me an idea of what could be going on.

I found this change from a while ago that _could_ be related but it's hard to tell: https://github.com/Azure/azure-functions-dotnet-worker/commit/86367157352fe3e57560826e5b7165151004c7cc

**Comment by kshyju** [comment] 2023-12-05 17:44
Closing as dupe of #2114 . See https://github.com/Azure/azure-functions-dotnet-worker/issues/2114#issuecomment-1840088691

**Closed by kshyju** 2023-12-05 17:44 UTC
