### ISSUE TITLE
.NET Framework 4.8 isolated - GA

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#924] opened 2022-06-13 23:15 UTC
Shipping list for .NET Framework 4.8 with Isolated worker tracking : 

- Templates - Visual Studio - UI experience
- Debugger - blocking issue 

Other related work : 
Update templates for isolated Azure functions  .NET framework 4.8
https://github.com/Azure/azure-functions-templates/issues/1225

CC. @fabiocav @mattchenderson

**Comment by satvu** [comment] 2022-06-15 18:15
Dupe of https://github.com/Azure/azure-functions-host/issues/8245

**Closed by satvu** 2022-06-15 18:15 UTC
Labels: Needs: Triage (Functions)
