### ISSUE TITLE
Guid as a route parameter not working

### ISSUE THREAD

**Issue by jp1482** [Azure/azure-functions-dotnet-worker#581] opened 2021-08-18 15:09 UTC
Following is my function signatute.

```
public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "test/{id:guid?}")] HttpRequestData req,
            Guid id,
            FunctionContext executionContext)
```
Steps
1. Now when I run the function it build and run file. Now lets assume that my function end point is http://localhost:7071/api/test/d38b8c35-d2bd-42ad-966e-933f9e8d36df .
2. Now this url throw exception with message

Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'Function1': Cannot convert input parameter 'id' to type 'System.Guid' from type 'System.String'.

3.  Now if I change Guid to string then it is working fine..

I have checked the worker code and it seems that there is no converter for Guid.  

Note: One can suggest that bind string and then use Guid.Parse but why it is not there.

**Comment by fabiocav** [comment] 2021-08-18 16:16
Duplicate of #521 

@jp1482 thank you for opening this. We have an issue tracking this (and currently assigned to a spring) here #521 

We'll close this and continue to follow up in the other issue.

**Closed by fabiocav** 2021-08-18 16:16 UTC
Labels: Needs: Triage (Functions)
