### ISSUE TITLE
Random fails in CI CD pipeline: error MSB3677: Unable to move file. Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by davidpetric** [Azure/azure-functions-dotnet-worker#2004] opened 2023-11-01 08:13 UTC
Having this issue randomly failing our CI/CD pipeline.

.csproj:

```xml
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>
  
 
    <ItemGroup>
     <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.14.1" />
      <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Core" Version="1.15.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Abstractions" Version="1.3.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.2" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
  </ItemGroup>
```
The error says

```
C:\Users\AzDevOps\.nuget\packages\microsoft.net.sdk.functions\4.2.0\build\Microsoft.NET.Sdk.Functions.Publish.targets(144,5): error MSB3677: Unable to move file "C:\Users\AzDevOps\AppData\Local\Temp\1\ssdk01mh.2d4\publishout\Microsoft.AspNetCore.Mvc.Formatters.Json.dll" to "C:\Users\AzDevOps\AppData\Local\Temp\1\ssdk01mh.2d4\publishout\bin\Microsoft.AspNetCore.Mvc.Formatters.Json.dll". Cannot create a file when that file already exists. [C:\Users\AzDevOps\AppData\Local\Temp\1\ssdk01mh.2d4\WorkerExtensions.csproj]
```

**Comment by jviau** [comment] 2023-11-08 21:36
Duplicate of #1834

**Closed by jviau** 2023-11-08 21:36 UTC
