### ISSUE TITLE
Unable to use Newtonsoft as default serializer

### ISSUE THREAD

**Issue by spplante** [Azure/azure-functions-dotnet-worker#2403] opened 2024-04-17 19:07 UTC
### Description

I have an isolated .NET8 Function App and I am unable to use Newtonsoft as a default serializer.

According to the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#customizing-json-serialization), the following can be added to the Program.cs in order to set the default serializer :

```C#
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication((IFunctionsWorkerApplicationBuilder builder) =>
    {
        builder.Services.Configure<WorkerOptions>(workerOptions =>
        {
            var settings = NewtonsoftJsonObjectSerializer.CreateJsonSerializerSettings();
            settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            settings.NullValueHandling = NullValueHandling.Ignore;

            workerOptions.Serializer = new NewtonsoftJsonObjectSerializer(settings);
        });
    })
    .Build();
```

However, this does absolutely nothing. No matter the serializer settings, it looks like it is still using System.Text.Json for serializing. I can even set the serializer to null and it changes nothing :

```C#
workerOptions.Serializer =null;
```

For now, as a workaround, I have installed **Microsoft.AspNetCore.Mvc.NewtonsoftJson** and used the following line:

```C#
.ConfigureServices((hostContext, services) =>
{
    services.AddMvcCore().AddNewtonsoftJson();
}
```

This works as expected, but I am not sure about the impact it could have over the solution and I would much rather use the officiel documented way, but the latter simply doesn't work.

Is the documentation wrong or is it a bug in the worker?

### Steps to reproduce

- Create a brand new .net8 isolated Function App

- Add the [code](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#customizing-json-serialization) to Program.cs to set Newtonsoft as default

- Run code and notice how it is still using **System.Text.Json** to serialize. You can try playing with the serializer options and you will also notice that it is completely ignored.

**Comment by liliankasem** [comment] 2024-04-18 19:21
I think I found this issue as well whilst investigating https://github.com/Azure/azure-functions-dotnet-worker/issues/2384

It looks like there is a bug with `ConfigureFunctionsWebApplication` where we are not properly registering customer provided serializers. We will need to investigate why the behavior seems to differ between `ConfigureFunctionsWebApplication` and `ConfigureFunctionsWorkerDefaults` as the latter is working as expected.

Flagging for investigation.

**Comment by liliankasem** [comment] 2024-04-23 20:10
Looks like this is a dupe of https://github.com/Azure/azure-functions-dotnet-worker/issues/2131

Closing in favour of using #2131 to track investigation and fix.

**Closed by liliankasem** 2024-04-23 20:10 UTC
Labels: bug, needs-investigation
